// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: bag.proto

package bag

import (
	common "chenxiao/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 背包物品（可堆叠：材料/消耗品/碎片；装备走 equip 模块）
type BagItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                           // 实例 ID
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`       // 物品配置 ID
	ItemType      int32                  `protobuf:"varint,3,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // 类型 1=材料 2=消耗品 3=碎片 4=其他
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	IsBound       bool                   `protobuf:"varint,5,opt,name=is_bound,json=isBound,proto3" json:"is_bound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagItem) Reset() {
	*x = BagItem{}
	mi := &file_bag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagItem) ProtoMessage() {}

func (x *BagItem) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagItem.ProtoReflect.Descriptor instead.
func (*BagItem) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{0}
}

func (x *BagItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BagItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BagItem) GetItemType() int32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *BagItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BagItem) GetIsBound() bool {
	if x != nil {
		return x.IsBound
	}
	return false
}

// 背包列表
type C2SBagList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SBagList) Reset() {
	*x = C2SBagList{}
	mi := &file_bag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SBagList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SBagList) ProtoMessage() {}

func (x *C2SBagList) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SBagList.ProtoReflect.Descriptor instead.
func (*C2SBagList) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{1}
}

type S2CBagList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Items         []*BagItem             `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CBagList) Reset() {
	*x = S2CBagList{}
	mi := &file_bag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CBagList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CBagList) ProtoMessage() {}

func (x *S2CBagList) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CBagList.ProtoReflect.Descriptor instead.
func (*S2CBagList) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{2}
}

func (x *S2CBagList) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CBagList) GetItems() []*BagItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 使用物品
type C2SBagUseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SBagUseItem) Reset() {
	*x = C2SBagUseItem{}
	mi := &file_bag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SBagUseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SBagUseItem) ProtoMessage() {}

func (x *C2SBagUseItem) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SBagUseItem.ProtoReflect.Descriptor instead.
func (*C2SBagUseItem) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{3}
}

func (x *C2SBagUseItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *C2SBagUseItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type S2CBagUseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Rewards       []*common.RewardItem   `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"` // 使用后产出
	Item          *BagItem               `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`       // 剩余数量（0 表示已用完）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CBagUseItem) Reset() {
	*x = S2CBagUseItem{}
	mi := &file_bag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CBagUseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CBagUseItem) ProtoMessage() {}

func (x *S2CBagUseItem) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CBagUseItem.ProtoReflect.Descriptor instead.
func (*S2CBagUseItem) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{4}
}

func (x *S2CBagUseItem) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CBagUseItem) GetRewards() []*common.RewardItem {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *S2CBagUseItem) GetItem() *BagItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_bag_proto protoreflect.FileDescriptor

const file_bag_proto_rawDesc = "" +
	"\n" +
	"\tbag.proto\x12\fchenxiao.bag\x1a\fcommon.proto\"\x82\x01\n" +
	"\aBagItem\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x1b\n" +
	"\titem_type\x18\x03 \x01(\x05R\bitemType\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12\x19\n" +
	"\bis_bound\x18\x05 \x01(\bR\aisBound\"\f\n" +
	"\n" +
	"C2SBagList\"j\n" +
	"\n" +
	"S2CBagList\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.chenxiao.bag.BagItemR\x05items\"7\n" +
	"\rC2SBagUseItem\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xa2\x01\n" +
	"\rS2CBagUseItem\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x125\n" +
	"\arewards\x18\x02 \x03(\v2\x1b.chenxiao.common.RewardItemR\arewards\x12)\n" +
	"\x04item\x18\x03 \x01(\v2\x15.chenxiao.bag.BagItemR\x04itemB\x18Z\x16chenxiao/proto/bag;bagb\x06proto3"

var (
	file_bag_proto_rawDescOnce sync.Once
	file_bag_proto_rawDescData []byte
)

func file_bag_proto_rawDescGZIP() []byte {
	file_bag_proto_rawDescOnce.Do(func() {
		file_bag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bag_proto_rawDesc), len(file_bag_proto_rawDesc)))
	})
	return file_bag_proto_rawDescData
}

var file_bag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bag_proto_goTypes = []any{
	(*BagItem)(nil),           // 0: chenxiao.bag.BagItem
	(*C2SBagList)(nil),        // 1: chenxiao.bag.C2SBagList
	(*S2CBagList)(nil),        // 2: chenxiao.bag.S2CBagList
	(*C2SBagUseItem)(nil),     // 3: chenxiao.bag.C2SBagUseItem
	(*S2CBagUseItem)(nil),     // 4: chenxiao.bag.S2CBagUseItem
	(*common.Result)(nil),     // 5: chenxiao.common.Result
	(*common.RewardItem)(nil), // 6: chenxiao.common.RewardItem
}
var file_bag_proto_depIdxs = []int32{
	5, // 0: chenxiao.bag.S2CBagList.result:type_name -> chenxiao.common.Result
	0, // 1: chenxiao.bag.S2CBagList.items:type_name -> chenxiao.bag.BagItem
	5, // 2: chenxiao.bag.S2CBagUseItem.result:type_name -> chenxiao.common.Result
	6, // 3: chenxiao.bag.S2CBagUseItem.rewards:type_name -> chenxiao.common.RewardItem
	0, // 4: chenxiao.bag.S2CBagUseItem.item:type_name -> chenxiao.bag.BagItem
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bag_proto_init() }
func file_bag_proto_init() {
	if File_bag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bag_proto_rawDesc), len(file_bag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bag_proto_goTypes,
		DependencyIndexes: file_bag_proto_depIdxs,
		MessageInfos:      file_bag_proto_msgTypes,
	}.Build()
	File_bag_proto = out.File
	file_bag_proto_goTypes = nil
	file_bag_proto_depIdxs = nil
}
