// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: ad.proto

package ad

import (
	common "chenxiao/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求观看广告
type C2SAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scene         int32                  `protobuf:"varint,1,opt,name=scene,proto3" json:"scene,omitempty"` // 场景：1=挂机倍率 2=材料 3=复活 4=翻倍 5=其他
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SAdRequest) Reset() {
	*x = C2SAdRequest{}
	mi := &file_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAdRequest) ProtoMessage() {}

func (x *C2SAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAdRequest.ProtoReflect.Descriptor instead.
func (*C2SAdRequest) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{0}
}

func (x *C2SAdRequest) GetScene() int32 {
	if x != nil {
		return x.Scene
	}
	return 0
}

type S2CAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	BizId         string                 `protobuf:"bytes,2,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`                    // 本次广告请求幂等键，上报时回传
	RemainTimes   int32                  `protobuf:"varint,3,opt,name=remain_times,json=remainTimes,proto3" json:"remain_times,omitempty"` // 今日剩余可观看次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CAdRequest) Reset() {
	*x = S2CAdRequest{}
	mi := &file_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAdRequest) ProtoMessage() {}

func (x *S2CAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAdRequest.ProtoReflect.Descriptor instead.
func (*S2CAdRequest) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{1}
}

func (x *S2CAdRequest) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CAdRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *S2CAdRequest) GetRemainTimes() int32 {
	if x != nil {
		return x.RemainTimes
	}
	return 0
}

// 观看完成上报
type C2SAdReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SAdReport) Reset() {
	*x = C2SAdReport{}
	mi := &file_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SAdReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAdReport) ProtoMessage() {}

func (x *C2SAdReport) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAdReport.ProtoReflect.Descriptor instead.
func (*C2SAdReport) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{2}
}

func (x *C2SAdReport) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

type S2CAdReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Rewards       []*common.RewardItem   `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"` // 本次发放奖励
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CAdReport) Reset() {
	*x = S2CAdReport{}
	mi := &file_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAdReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAdReport) ProtoMessage() {}

func (x *S2CAdReport) ProtoReflect() protoreflect.Message {
	mi := &file_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAdReport.ProtoReflect.Descriptor instead.
func (*S2CAdReport) Descriptor() ([]byte, []int) {
	return file_ad_proto_rawDescGZIP(), []int{3}
}

func (x *S2CAdReport) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CAdReport) GetRewards() []*common.RewardItem {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_ad_proto protoreflect.FileDescriptor

const file_ad_proto_rawDesc = "" +
	"\n" +
	"\bad.proto\x12\vchenxiao.ad\x1a\fcommon.proto\"$\n" +
	"\fC2SAdRequest\x12\x14\n" +
	"\x05scene\x18\x01 \x01(\x05R\x05scene\"y\n" +
	"\fS2CAdRequest\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12\x15\n" +
	"\x06biz_id\x18\x02 \x01(\tR\x05bizId\x12!\n" +
	"\fremain_times\x18\x03 \x01(\x05R\vremainTimes\"$\n" +
	"\vC2SAdReport\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\tR\x05bizId\"u\n" +
	"\vS2CAdReport\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x125\n" +
	"\arewards\x18\x02 \x03(\v2\x1b.chenxiao.common.RewardItemR\arewardsB\x16Z\x14chenxiao/proto/ad;adb\x06proto3"

var (
	file_ad_proto_rawDescOnce sync.Once
	file_ad_proto_rawDescData []byte
)

func file_ad_proto_rawDescGZIP() []byte {
	file_ad_proto_rawDescOnce.Do(func() {
		file_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ad_proto_rawDesc), len(file_ad_proto_rawDesc)))
	})
	return file_ad_proto_rawDescData
}

var file_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ad_proto_goTypes = []any{
	(*C2SAdRequest)(nil),      // 0: chenxiao.ad.C2SAdRequest
	(*S2CAdRequest)(nil),      // 1: chenxiao.ad.S2CAdRequest
	(*C2SAdReport)(nil),       // 2: chenxiao.ad.C2SAdReport
	(*S2CAdReport)(nil),       // 3: chenxiao.ad.S2CAdReport
	(*common.Result)(nil),     // 4: chenxiao.common.Result
	(*common.RewardItem)(nil), // 5: chenxiao.common.RewardItem
}
var file_ad_proto_depIdxs = []int32{
	4, // 0: chenxiao.ad.S2CAdRequest.result:type_name -> chenxiao.common.Result
	4, // 1: chenxiao.ad.S2CAdReport.result:type_name -> chenxiao.common.Result
	5, // 2: chenxiao.ad.S2CAdReport.rewards:type_name -> chenxiao.common.RewardItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ad_proto_init() }
func file_ad_proto_init() {
	if File_ad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ad_proto_rawDesc), len(file_ad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ad_proto_goTypes,
		DependencyIndexes: file_ad_proto_depIdxs,
		MessageInfos:      file_ad_proto_msgTypes,
	}.Build()
	File_ad_proto = out.File
	file_ad_proto_goTypes = nil
	file_ad_proto_depIdxs = nil
}
