// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: login.proto

package login

import (
	common "chenxiao/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色快照（登录 / 创建角色 / 推送共用）
type RoleBrief struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerId            int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname            string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar              string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Level               int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp                 int64                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`                                                                 // 修为
	Copper              int64                  `protobuf:"varint,6,opt,name=copper,proto3" json:"copper,omitempty"`                                                           // 铜钱
	Power               int64                  `protobuf:"varint,7,opt,name=power,proto3" json:"power,omitempty"`                                                             // 战力
	NormalStageId       int32                  `protobuf:"varint,8,opt,name=normal_stage_id,json=normalStageId,proto3" json:"normal_stage_id,omitempty"`                      // 普通关卡最高已通关 ID
	EliteStageId        int32                  `protobuf:"varint,9,opt,name=elite_stage_id,json=eliteStageId,proto3" json:"elite_stage_id,omitempty"`                         // 精英关卡最高已通关 ID
	BossStageId         int32                  `protobuf:"varint,10,opt,name=boss_stage_id,json=bossStageId,proto3" json:"boss_stage_id,omitempty"`                           // BOSS 关卡最高已通关 ID
	LastOfflineSettleAt int64                  `protobuf:"varint,11,opt,name=last_offline_settle_at,json=lastOfflineSettleAt,proto3" json:"last_offline_settle_at,omitempty"` // 上次离线结算截止时间（Unix 秒）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RoleBrief) Reset() {
	*x = RoleBrief{}
	mi := &file_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBrief) ProtoMessage() {}

func (x *RoleBrief) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBrief.ProtoReflect.Descriptor instead.
func (*RoleBrief) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{0}
}

func (x *RoleBrief) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RoleBrief) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoleBrief) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RoleBrief) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoleBrief) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *RoleBrief) GetCopper() int64 {
	if x != nil {
		return x.Copper
	}
	return 0
}

func (x *RoleBrief) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *RoleBrief) GetNormalStageId() int32 {
	if x != nil {
		return x.NormalStageId
	}
	return 0
}

func (x *RoleBrief) GetEliteStageId() int32 {
	if x != nil {
		return x.EliteStageId
	}
	return 0
}

func (x *RoleBrief) GetBossStageId() int32 {
	if x != nil {
		return x.BossStageId
	}
	return 0
}

func (x *RoleBrief) GetLastOfflineSettleAt() int64 {
	if x != nil {
		return x.LastOfflineSettleAt
	}
	return 0
}

// 登录：wx.login 的 code 换 openid
type C2SLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                               // wx.login 返回的临时 code
	DeviceInfo    string                 `protobuf:"bytes,2,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"` // 设备信息（可选，日志用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SLogin) Reset() {
	*x = C2SLogin{}
	mi := &file_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SLogin) ProtoMessage() {}

func (x *C2SLogin) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SLogin.ProtoReflect.Descriptor instead.
func (*C2SLogin) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{1}
}

func (x *C2SLogin) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *C2SLogin) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

type S2CLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                     // 会话 token，后续请求在包头携带
	HasRole       bool                   `protobuf:"varint,3,opt,name=has_role,json=hasRole,proto3" json:"has_role,omitempty"` // 是否已创建角色
	Role          *RoleBrief             `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`                       // 已有角色时的快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CLogin) Reset() {
	*x = S2CLogin{}
	mi := &file_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CLogin) ProtoMessage() {}

func (x *S2CLogin) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CLogin.ProtoReflect.Descriptor instead.
func (*S2CLogin) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{2}
}

func (x *S2CLogin) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *S2CLogin) GetHasRole() bool {
	if x != nil {
		return x.HasRole
	}
	return false
}

func (x *S2CLogin) GetRole() *RoleBrief {
	if x != nil {
		return x.Role
	}
	return nil
}

// 创建角色
type C2SCreateRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarId      int32                  `protobuf:"varint,2,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"` // 头像资源 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SCreateRole) Reset() {
	*x = C2SCreateRole{}
	mi := &file_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SCreateRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCreateRole) ProtoMessage() {}

func (x *C2SCreateRole) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCreateRole.ProtoReflect.Descriptor instead.
func (*C2SCreateRole) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{3}
}

func (x *C2SCreateRole) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *C2SCreateRole) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

type S2CCreateRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Role          *RoleBrief             `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CCreateRole) Reset() {
	*x = S2CCreateRole{}
	mi := &file_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CCreateRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCreateRole) ProtoMessage() {}

func (x *S2CCreateRole) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCreateRole.ProtoReflect.Descriptor instead.
func (*S2CCreateRole) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{4}
}

func (x *S2CCreateRole) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CCreateRole) GetRole() *RoleBrief {
	if x != nil {
		return x.Role
	}
	return nil
}

// 服务端推送的角色快照（登录后 / 关键属性变更时下发）
type S2CRoleBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleBrief             `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CRoleBrief) Reset() {
	*x = S2CRoleBrief{}
	mi := &file_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CRoleBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRoleBrief) ProtoMessage() {}

func (x *S2CRoleBrief) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRoleBrief.ProtoReflect.Descriptor instead.
func (*S2CRoleBrief) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{5}
}

func (x *S2CRoleBrief) GetRole() *RoleBrief {
	if x != nil {
		return x.Role
	}
	return nil
}

var File_login_proto protoreflect.FileDescriptor

const file_login_proto_rawDesc = "" +
	"\n" +
	"\vlogin.proto\x12\x0echenxiao.login\x1a\fcommon.proto\"\xd9\x02\n" +
	"\tRoleBrief\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x03R\x03exp\x12\x16\n" +
	"\x06copper\x18\x06 \x01(\x03R\x06copper\x12\x14\n" +
	"\x05power\x18\a \x01(\x03R\x05power\x12&\n" +
	"\x0fnormal_stage_id\x18\b \x01(\x05R\rnormalStageId\x12$\n" +
	"\x0eelite_stage_id\x18\t \x01(\x05R\feliteStageId\x12\"\n" +
	"\rboss_stage_id\x18\n" +
	" \x01(\x05R\vbossStageId\x123\n" +
	"\x16last_offline_settle_at\x18\v \x01(\x03R\x13lastOfflineSettleAt\"?\n" +
	"\bC2SLogin\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1f\n" +
	"\vdevice_info\x18\x02 \x01(\tR\n" +
	"deviceInfo\"\x9b\x01\n" +
	"\bS2CLogin\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x19\n" +
	"\bhas_role\x18\x03 \x01(\bR\ahasRole\x12-\n" +
	"\x04role\x18\x04 \x01(\v2\x19.chenxiao.login.RoleBriefR\x04role\"H\n" +
	"\rC2SCreateRole\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1b\n" +
	"\tavatar_id\x18\x02 \x01(\x05R\bavatarId\"o\n" +
	"\rS2CCreateRole\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12-\n" +
	"\x04role\x18\x02 \x01(\v2\x19.chenxiao.login.RoleBriefR\x04role\"=\n" +
	"\fS2CRoleBrief\x12-\n" +
	"\x04role\x18\x01 \x01(\v2\x19.chenxiao.login.RoleBriefR\x04roleB\x1cZ\x1achenxiao/proto/login;loginb\x06proto3"

var (
	file_login_proto_rawDescOnce sync.Once
	file_login_proto_rawDescData []byte
)

func file_login_proto_rawDescGZIP() []byte {
	file_login_proto_rawDescOnce.Do(func() {
		file_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)))
	})
	return file_login_proto_rawDescData
}

var file_login_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_login_proto_goTypes = []any{
	(*RoleBrief)(nil),     // 0: chenxiao.login.RoleBrief
	(*C2SLogin)(nil),      // 1: chenxiao.login.C2SLogin
	(*S2CLogin)(nil),      // 2: chenxiao.login.S2CLogin
	(*C2SCreateRole)(nil), // 3: chenxiao.login.C2SCreateRole
	(*S2CCreateRole)(nil), // 4: chenxiao.login.S2CCreateRole
	(*S2CRoleBrief)(nil),  // 5: chenxiao.login.S2CRoleBrief
	(*common.Result)(nil), // 6: chenxiao.common.Result
}
var file_login_proto_depIdxs = []int32{
	6, // 0: chenxiao.login.S2CLogin.result:type_name -> chenxiao.common.Result
	0, // 1: chenxiao.login.S2CLogin.role:type_name -> chenxiao.login.RoleBrief
	6, // 2: chenxiao.login.S2CCreateRole.result:type_name -> chenxiao.common.Result
	0, // 3: chenxiao.login.S2CCreateRole.role:type_name -> chenxiao.login.RoleBrief
	0, // 4: chenxiao.login.S2CRoleBrief.role:type_name -> chenxiao.login.RoleBrief
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_login_proto_init() }
func file_login_proto_init() {
	if File_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_proto_goTypes,
		DependencyIndexes: file_login_proto_depIdxs,
		MessageInfos:      file_login_proto_msgTypes,
	}.Build()
	File_login_proto = out.File
	file_login_proto_goTypes = nil
	file_login_proto_depIdxs = nil
}
