// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: rank.proto

package rank

import (
	common "chenxiao/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 榜单条目
type RankEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankNo        int32                  `protobuf:"varint,1,opt,name=rank_no,json=rankNo,proto3" json:"rank_no,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Score         int64                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"` // 战力 / 层数 / 等级，依榜单类型而定
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankEntry) Reset() {
	*x = RankEntry{}
	mi := &file_rank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankEntry) ProtoMessage() {}

func (x *RankEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankEntry.ProtoReflect.Descriptor instead.
func (*RankEntry) Descriptor() ([]byte, []int) {
	return file_rank_proto_rawDescGZIP(), []int{0}
}

func (x *RankEntry) GetRankNo() int32 {
	if x != nil {
		return x.RankNo
	}
	return 0
}

func (x *RankEntry) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RankEntry) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RankEntry) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RankEntry) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RankEntry) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 查询排行榜
type C2SRankQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      int32                  `protobuf:"varint,1,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"` // 1=战力 2=秘境层数 3=等级
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 从 0 开始
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SRankQuery) Reset() {
	*x = C2SRankQuery{}
	mi := &file_rank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SRankQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRankQuery) ProtoMessage() {}

func (x *C2SRankQuery) ProtoReflect() protoreflect.Message {
	mi := &file_rank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRankQuery.ProtoReflect.Descriptor instead.
func (*C2SRankQuery) Descriptor() ([]byte, []int) {
	return file_rank_proto_rawDescGZIP(), []int{1}
}

func (x *C2SRankQuery) GetRankType() int32 {
	if x != nil {
		return x.RankType
	}
	return 0
}

func (x *C2SRankQuery) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *C2SRankQuery) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type S2CRankQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Entries       []*RankEntry           `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	MyRank        *RankEntry             `protobuf:"bytes,3,opt,name=my_rank,json=myRank,proto3" json:"my_rank,omitempty"` // 我的名次（未上榜可为空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CRankQuery) Reset() {
	*x = S2CRankQuery{}
	mi := &file_rank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CRankQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRankQuery) ProtoMessage() {}

func (x *S2CRankQuery) ProtoReflect() protoreflect.Message {
	mi := &file_rank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRankQuery.ProtoReflect.Descriptor instead.
func (*S2CRankQuery) Descriptor() ([]byte, []int) {
	return file_rank_proto_rawDescGZIP(), []int{2}
}

func (x *S2CRankQuery) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CRankQuery) GetEntries() []*RankEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *S2CRankQuery) GetMyRank() *RankEntry {
	if x != nil {
		return x.MyRank
	}
	return nil
}

var File_rank_proto protoreflect.FileDescriptor

const file_rank_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rank.proto\x12\rchenxiao.rank\x1a\fcommon.proto\"\xa1\x01\n" +
	"\tRankEntry\x12\x17\n" +
	"\arank_no\x18\x01 \x01(\x05R\x06rankNo\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x03R\x05score\"\\\n" +
	"\fC2SRankQuery\x12\x1b\n" +
	"\trank_type\x18\x01 \x01(\x05R\brankType\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa6\x01\n" +
	"\fS2CRankQuery\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x122\n" +
	"\aentries\x18\x02 \x03(\v2\x18.chenxiao.rank.RankEntryR\aentries\x121\n" +
	"\amy_rank\x18\x03 \x01(\v2\x18.chenxiao.rank.RankEntryR\x06myRankB\x1aZ\x18chenxiao/proto/rank;rankb\x06proto3"

var (
	file_rank_proto_rawDescOnce sync.Once
	file_rank_proto_rawDescData []byte
)

func file_rank_proto_rawDescGZIP() []byte {
	file_rank_proto_rawDescOnce.Do(func() {
		file_rank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rank_proto_rawDesc), len(file_rank_proto_rawDesc)))
	})
	return file_rank_proto_rawDescData
}

var file_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rank_proto_goTypes = []any{
	(*RankEntry)(nil),     // 0: chenxiao.rank.RankEntry
	(*C2SRankQuery)(nil),  // 1: chenxiao.rank.C2SRankQuery
	(*S2CRankQuery)(nil),  // 2: chenxiao.rank.S2CRankQuery
	(*common.Result)(nil), // 3: chenxiao.common.Result
}
var file_rank_proto_depIdxs = []int32{
	3, // 0: chenxiao.rank.S2CRankQuery.result:type_name -> chenxiao.common.Result
	0, // 1: chenxiao.rank.S2CRankQuery.entries:type_name -> chenxiao.rank.RankEntry
	0, // 2: chenxiao.rank.S2CRankQuery.my_rank:type_name -> chenxiao.rank.RankEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rank_proto_init() }
func file_rank_proto_init() {
	if File_rank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rank_proto_rawDesc), len(file_rank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rank_proto_goTypes,
		DependencyIndexes: file_rank_proto_depIdxs,
		MessageInfos:      file_rank_proto_msgTypes,
	}.Build()
	File_rank_proto = out.File
	file_rank_proto_goTypes = nil
	file_rank_proto_depIdxs = nil
}
