// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: mail.proto

package mail

import (
	common "chenxiao/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 邮件附件条目
type MailAttachment struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ItemId int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count  int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// 装备类附件（带实例）在此扩展
	EquipUid      int64 `protobuf:"varint,3,opt,name=equip_uid,json=equipUid,proto3" json:"equip_uid,omitempty"` // 装备实例 ID（0=非装备附件）
	EquipId       int32 `protobuf:"varint,4,opt,name=equip_id,json=equipId,proto3" json:"equip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailAttachment) Reset() {
	*x = MailAttachment{}
	mi := &file_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailAttachment) ProtoMessage() {}

func (x *MailAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailAttachment.ProtoReflect.Descriptor instead.
func (*MailAttachment) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

func (x *MailAttachment) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *MailAttachment) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MailAttachment) GetEquipUid() int64 {
	if x != nil {
		return x.EquipUid
	}
	return 0
}

func (x *MailAttachment) GetEquipId() int32 {
	if x != nil {
		return x.EquipId
	}
	return 0
}

// 邮件
type MailInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailId        int64                  `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	MailType      int32                  `protobuf:"varint,2,opt,name=mail_type,json=mailType,proto3" json:"mail_type,omitempty"` // 1=系统 2=补偿 3=活动
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Attachments   []*MailAttachment      `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	IsRead        bool                   `protobuf:"varint,6,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	IsClaimed     bool                   `protobuf:"varint,7,opt,name=is_claimed,json=isClaimed,proto3" json:"is_claimed,omitempty"` // 附件是否已领取
	ExpireAt      int64                  `protobuf:"varint,8,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`    // 过期时间（Unix 秒，0=不过期）
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailInfo) Reset() {
	*x = MailInfo{}
	mi := &file_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailInfo) ProtoMessage() {}

func (x *MailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailInfo.ProtoReflect.Descriptor instead.
func (*MailInfo) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{1}
}

func (x *MailInfo) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

func (x *MailInfo) GetMailType() int32 {
	if x != nil {
		return x.MailType
	}
	return 0
}

func (x *MailInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MailInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MailInfo) GetAttachments() []*MailAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *MailInfo) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *MailInfo) GetIsClaimed() bool {
	if x != nil {
		return x.IsClaimed
	}
	return false
}

func (x *MailInfo) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *MailInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 邮件列表
type C2SMailList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SMailList) Reset() {
	*x = C2SMailList{}
	mi := &file_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SMailList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMailList) ProtoMessage() {}

func (x *C2SMailList) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMailList.ProtoReflect.Descriptor instead.
func (*C2SMailList) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{2}
}

type S2CMailList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Mails         []*MailInfo            `protobuf:"bytes,2,rep,name=mails,proto3" json:"mails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CMailList) Reset() {
	*x = S2CMailList{}
	mi := &file_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CMailList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMailList) ProtoMessage() {}

func (x *S2CMailList) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMailList.ProtoReflect.Descriptor instead.
func (*S2CMailList) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{3}
}

func (x *S2CMailList) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CMailList) GetMails() []*MailInfo {
	if x != nil {
		return x.Mails
	}
	return nil
}

// 已读
type C2SMailRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailId        int64                  `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SMailRead) Reset() {
	*x = C2SMailRead{}
	mi := &file_mail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SMailRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMailRead) ProtoMessage() {}

func (x *C2SMailRead) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMailRead.ProtoReflect.Descriptor instead.
func (*C2SMailRead) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{4}
}

func (x *C2SMailRead) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type S2CMailRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	MailId        int64                  `protobuf:"varint,2,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CMailRead) Reset() {
	*x = S2CMailRead{}
	mi := &file_mail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CMailRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMailRead) ProtoMessage() {}

func (x *S2CMailRead) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMailRead.ProtoReflect.Descriptor instead.
func (*S2CMailRead) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{5}
}

func (x *S2CMailRead) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CMailRead) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

// 领取附件
type C2SMailClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailId        int64                  `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SMailClaim) Reset() {
	*x = C2SMailClaim{}
	mi := &file_mail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SMailClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMailClaim) ProtoMessage() {}

func (x *C2SMailClaim) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMailClaim.ProtoReflect.Descriptor instead.
func (*C2SMailClaim) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{6}
}

func (x *C2SMailClaim) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type S2CMailClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	MailId        int64                  `protobuf:"varint,2,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	Rewards       []*common.RewardItem   `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CMailClaim) Reset() {
	*x = S2CMailClaim{}
	mi := &file_mail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CMailClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMailClaim) ProtoMessage() {}

func (x *S2CMailClaim) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMailClaim.ProtoReflect.Descriptor instead.
func (*S2CMailClaim) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{7}
}

func (x *S2CMailClaim) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CMailClaim) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

func (x *S2CMailClaim) GetRewards() []*common.RewardItem {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_mail_proto protoreflect.FileDescriptor

const file_mail_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mail.proto\x12\rchenxiao.mail\x1a\fcommon.proto\"w\n" +
	"\x0eMailAttachment\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x1b\n" +
	"\tequip_uid\x18\x03 \x01(\x03R\bequipUid\x12\x19\n" +
	"\bequip_id\x18\x04 \x01(\x05R\aequipId\"\xa5\x02\n" +
	"\bMailInfo\x12\x17\n" +
	"\amail_id\x18\x01 \x01(\x03R\x06mailId\x12\x1b\n" +
	"\tmail_type\x18\x02 \x01(\x05R\bmailType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12?\n" +
	"\vattachments\x18\x05 \x03(\v2\x1d.chenxiao.mail.MailAttachmentR\vattachments\x12\x17\n" +
	"\ais_read\x18\x06 \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"is_claimed\x18\a \x01(\bR\tisClaimed\x12\x1b\n" +
	"\texpire_at\x18\b \x01(\x03R\bexpireAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"\r\n" +
	"\vC2SMailList\"m\n" +
	"\vS2CMailList\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12-\n" +
	"\x05mails\x18\x02 \x03(\v2\x17.chenxiao.mail.MailInfoR\x05mails\"&\n" +
	"\vC2SMailRead\x12\x17\n" +
	"\amail_id\x18\x01 \x01(\x03R\x06mailId\"W\n" +
	"\vS2CMailRead\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12\x17\n" +
	"\amail_id\x18\x02 \x01(\x03R\x06mailId\"'\n" +
	"\fC2SMailClaim\x12\x17\n" +
	"\amail_id\x18\x01 \x01(\x03R\x06mailId\"\x8f\x01\n" +
	"\fS2CMailClaim\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12\x17\n" +
	"\amail_id\x18\x02 \x01(\x03R\x06mailId\x125\n" +
	"\arewards\x18\x03 \x03(\v2\x1b.chenxiao.common.RewardItemR\arewardsB\x1aZ\x18chenxiao/proto/mail;mailb\x06proto3"

var (
	file_mail_proto_rawDescOnce sync.Once
	file_mail_proto_rawDescData []byte
)

func file_mail_proto_rawDescGZIP() []byte {
	file_mail_proto_rawDescOnce.Do(func() {
		file_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mail_proto_rawDesc), len(file_mail_proto_rawDesc)))
	})
	return file_mail_proto_rawDescData
}

var file_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mail_proto_goTypes = []any{
	(*MailAttachment)(nil),    // 0: chenxiao.mail.MailAttachment
	(*MailInfo)(nil),          // 1: chenxiao.mail.MailInfo
	(*C2SMailList)(nil),       // 2: chenxiao.mail.C2SMailList
	(*S2CMailList)(nil),       // 3: chenxiao.mail.S2CMailList
	(*C2SMailRead)(nil),       // 4: chenxiao.mail.C2SMailRead
	(*S2CMailRead)(nil),       // 5: chenxiao.mail.S2CMailRead
	(*C2SMailClaim)(nil),      // 6: chenxiao.mail.C2SMailClaim
	(*S2CMailClaim)(nil),      // 7: chenxiao.mail.S2CMailClaim
	(*common.Result)(nil),     // 8: chenxiao.common.Result
	(*common.RewardItem)(nil), // 9: chenxiao.common.RewardItem
}
var file_mail_proto_depIdxs = []int32{
	0, // 0: chenxiao.mail.MailInfo.attachments:type_name -> chenxiao.mail.MailAttachment
	8, // 1: chenxiao.mail.S2CMailList.result:type_name -> chenxiao.common.Result
	1, // 2: chenxiao.mail.S2CMailList.mails:type_name -> chenxiao.mail.MailInfo
	8, // 3: chenxiao.mail.S2CMailRead.result:type_name -> chenxiao.common.Result
	8, // 4: chenxiao.mail.S2CMailClaim.result:type_name -> chenxiao.common.Result
	9, // 5: chenxiao.mail.S2CMailClaim.rewards:type_name -> chenxiao.common.RewardItem
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_mail_proto_init() }
func file_mail_proto_init() {
	if File_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mail_proto_rawDesc), len(file_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mail_proto_goTypes,
		DependencyIndexes: file_mail_proto_depIdxs,
		MessageInfos:      file_mail_proto_msgTypes,
	}.Build()
	File_mail_proto = out.File
	file_mail_proto_goTypes = nil
	file_mail_proto_depIdxs = nil
}
