// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============================================================
// 错误码
// 区间规划：1xxx 登录/角色  2xxx 资源  3xxx 装备  4xxx 灵宠
//
//	5xxx 关卡  6xxx 邮件  7xxx 广告
//
// ============================================================
type ErrorCode int32

const (
	ErrorCode_OK ErrorCode = 0
	// ---- 通用 ----
	ErrorCode_ERR_INTERNAL      ErrorCode = 1 // 内部错误
	ErrorCode_ERR_INVALID_PARAM ErrorCode = 2 // 参数非法
	ErrorCode_ERR_NOT_LOGIN     ErrorCode = 3 // 未登录
	ErrorCode_ERR_TOKEN_EXPIRED ErrorCode = 4 // 会话过期
	ErrorCode_ERR_KICKED        ErrorCode = 5 // 被顶号/踢下线
	ErrorCode_ERR_MAINTENANCE   ErrorCode = 6 // 停服维护
	ErrorCode_ERR_RATE_LIMIT    ErrorCode = 7 // 请求过频
	// ---- 登录/角色 1xxx ----
	ErrorCode_ERR_LOGIN_CODE_INVALID ErrorCode = 1001 // code 换取 openid 失败
	ErrorCode_ERR_ROLE_EXISTS        ErrorCode = 1002 // 已创建角色
	ErrorCode_ERR_ROLE_NOT_EXISTS    ErrorCode = 1003 // 角色不存在
	ErrorCode_ERR_NAME_INVALID       ErrorCode = 1004 // 昵称非法(敏感词/长度)
	// ---- 资源 2xxx ----
	ErrorCode_ERR_COPPER_NOT_ENOUGH   ErrorCode = 2001 // 铜钱不足
	ErrorCode_ERR_MATERIAL_NOT_ENOUGH ErrorCode = 2002 // 材料不足
	// ---- 装备 3xxx ----
	ErrorCode_ERR_EQUIP_NOT_FOUND      ErrorCode = 3001 // 装备不存在
	ErrorCode_ERR_EQUIP_POS_INVALID    ErrorCode = 3002 // 穿戴部位非法
	ErrorCode_ERR_STRENGTHEN_LEVEL_MAX ErrorCode = 3003 // 强化已满级
	// ---- 灵宠 4xxx ----
	ErrorCode_ERR_PET_NOT_FOUND ErrorCode = 4001 // 灵宠不存在
	ErrorCode_ERR_PET_MAX       ErrorCode = 4002 // 灵宠数量上限
	// ---- 关卡 5xxx ----
	ErrorCode_ERR_STAGE_LOCKED      ErrorCode = 5001 // 关卡未解锁
	ErrorCode_ERR_STAGE_TIMES_LIMIT ErrorCode = 5002 // 挑战次数已耗尽
	// ---- 邮件 6xxx ----
	ErrorCode_ERR_MAIL_NOT_FOUND       ErrorCode = 6001 // 邮件不存在
	ErrorCode_ERR_MAIL_ALREADY_CLAIMED ErrorCode = 6002 // 附件已领取
	// ---- 广告 7xxx ----
	ErrorCode_ERR_AD_NOT_COMPLETED ErrorCode = 7001 // 广告未完成
	ErrorCode_ERR_AD_LIMIT         ErrorCode = 7002 // 今日次数已满
	ErrorCode_ERR_AD_DUPLICATE     ErrorCode = 7003 // 重复上报(biz_id 已用)
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "OK",
		1:    "ERR_INTERNAL",
		2:    "ERR_INVALID_PARAM",
		3:    "ERR_NOT_LOGIN",
		4:    "ERR_TOKEN_EXPIRED",
		5:    "ERR_KICKED",
		6:    "ERR_MAINTENANCE",
		7:    "ERR_RATE_LIMIT",
		1001: "ERR_LOGIN_CODE_INVALID",
		1002: "ERR_ROLE_EXISTS",
		1003: "ERR_ROLE_NOT_EXISTS",
		1004: "ERR_NAME_INVALID",
		2001: "ERR_COPPER_NOT_ENOUGH",
		2002: "ERR_MATERIAL_NOT_ENOUGH",
		3001: "ERR_EQUIP_NOT_FOUND",
		3002: "ERR_EQUIP_POS_INVALID",
		3003: "ERR_STRENGTHEN_LEVEL_MAX",
		4001: "ERR_PET_NOT_FOUND",
		4002: "ERR_PET_MAX",
		5001: "ERR_STAGE_LOCKED",
		5002: "ERR_STAGE_TIMES_LIMIT",
		6001: "ERR_MAIL_NOT_FOUND",
		6002: "ERR_MAIL_ALREADY_CLAIMED",
		7001: "ERR_AD_NOT_COMPLETED",
		7002: "ERR_AD_LIMIT",
		7003: "ERR_AD_DUPLICATE",
	}
	ErrorCode_value = map[string]int32{
		"OK":                       0,
		"ERR_INTERNAL":             1,
		"ERR_INVALID_PARAM":        2,
		"ERR_NOT_LOGIN":            3,
		"ERR_TOKEN_EXPIRED":        4,
		"ERR_KICKED":               5,
		"ERR_MAINTENANCE":          6,
		"ERR_RATE_LIMIT":           7,
		"ERR_LOGIN_CODE_INVALID":   1001,
		"ERR_ROLE_EXISTS":          1002,
		"ERR_ROLE_NOT_EXISTS":      1003,
		"ERR_NAME_INVALID":         1004,
		"ERR_COPPER_NOT_ENOUGH":    2001,
		"ERR_MATERIAL_NOT_ENOUGH":  2002,
		"ERR_EQUIP_NOT_FOUND":      3001,
		"ERR_EQUIP_POS_INVALID":    3002,
		"ERR_STRENGTHEN_LEVEL_MAX": 3003,
		"ERR_PET_NOT_FOUND":        4001,
		"ERR_PET_MAX":              4002,
		"ERR_STAGE_LOCKED":         5001,
		"ERR_STAGE_TIMES_LIMIT":    5002,
		"ERR_MAIL_NOT_FOUND":       6001,
		"ERR_MAIL_ALREADY_CLAIMED": 6002,
		"ERR_AD_NOT_COMPLETED":     7001,
		"ERR_AD_LIMIT":             7002,
		"ERR_AD_DUPLICATE":         7003,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// ============================================================
// 消息 ID 注册表
// 约定：C2S 为偶数，S2C 为其 +1；服务端按 MsgId 路由到对应 handler
// ============================================================
type MsgId int32

const (
	MsgId_MSG_ID_NONE MsgId = 0
	// ---- 心跳/通用 1-99 ----
	MsgId_C2S_HEARTBEAT MsgId = 1
	MsgId_S2C_HEARTBEAT MsgId = 2
	MsgId_S2C_KICK      MsgId = 3
	// ---- 登录/角色 1000-1099 ----
	MsgId_C2S_LOGIN       MsgId = 1000
	MsgId_S2C_LOGIN       MsgId = 1001
	MsgId_C2S_CREATE_ROLE MsgId = 1002
	MsgId_S2C_CREATE_ROLE MsgId = 1003
	MsgId_S2C_ROLE_BRIEF  MsgId = 1004 // 服务端推送的角色快照
	// ---- 挂机/离线 2000-2099 ----
	MsgId_C2S_OFFLINE_REWARD_QUERY MsgId = 2000
	MsgId_S2C_OFFLINE_REWARD_QUERY MsgId = 2001
	MsgId_C2S_OFFLINE_REWARD_CLAIM MsgId = 2002
	MsgId_S2C_OFFLINE_REWARD_CLAIM MsgId = 2003
	MsgId_C2S_HANG_REWARD_QUERY    MsgId = 2004 // 在线挂机收益查询
	MsgId_S2C_HANG_REWARD_QUERY    MsgId = 2005
	MsgId_C2S_HANG_REWARD_CLAIM    MsgId = 2006
	MsgId_S2C_HANG_REWARD_CLAIM    MsgId = 2007
	// ---- 秘境/战斗 3000-3099 ----
	MsgId_C2S_START_STAGE MsgId = 3000
	MsgId_S2C_START_STAGE MsgId = 3001
	MsgId_C2S_SWEEP_STAGE MsgId = 3002 // 扫荡
	MsgId_S2C_SWEEP_STAGE MsgId = 3003
	// ---- 装备 4000-4099 ----
	MsgId_C2S_EQUIP_LIST       MsgId = 4000
	MsgId_S2C_EQUIP_LIST       MsgId = 4001
	MsgId_C2S_EQUIP_WEAR       MsgId = 4002
	MsgId_S2C_EQUIP_WEAR       MsgId = 4003
	MsgId_C2S_EQUIP_STRENGTHEN MsgId = 4004
	MsgId_S2C_EQUIP_STRENGTHEN MsgId = 4005
	MsgId_C2S_EQUIP_REFINE     MsgId = 4006
	MsgId_S2C_EQUIP_REFINE     MsgId = 4007
	MsgId_C2S_EQUIP_DECOMPOSE  MsgId = 4008
	MsgId_S2C_EQUIP_DECOMPOSE  MsgId = 4009
	// ---- 灵宠 5000-5099 ----
	MsgId_C2S_PET_LIST       MsgId = 5000
	MsgId_S2C_PET_LIST       MsgId = 5001
	MsgId_C2S_PET_SET_COMBAT MsgId = 5002
	MsgId_S2C_PET_SET_COMBAT MsgId = 5003
	MsgId_C2S_PET_UPGRADE    MsgId = 5004
	MsgId_S2C_PET_UPGRADE    MsgId = 5005
	MsgId_C2S_PET_EVOLVE     MsgId = 5006
	MsgId_S2C_PET_EVOLVE     MsgId = 5007
	// ---- 背包 6000-6099 ----
	MsgId_C2S_BAG_LIST     MsgId = 6000
	MsgId_S2C_BAG_LIST     MsgId = 6001
	MsgId_C2S_BAG_USE_ITEM MsgId = 6002
	MsgId_S2C_BAG_USE_ITEM MsgId = 6003
	// ---- 邮件 7000-7099 ----
	MsgId_C2S_MAIL_LIST  MsgId = 7000
	MsgId_S2C_MAIL_LIST  MsgId = 7001
	MsgId_C2S_MAIL_READ  MsgId = 7002
	MsgId_S2C_MAIL_READ  MsgId = 7003
	MsgId_C2S_MAIL_CLAIM MsgId = 7004
	MsgId_S2C_MAIL_CLAIM MsgId = 7005
	// ---- 排行榜 8000-8099 ----
	MsgId_C2S_RANK_QUERY MsgId = 8000
	MsgId_S2C_RANK_QUERY MsgId = 8001
	// ---- 广告 9000-9099 ----
	MsgId_C2S_AD_REQUEST MsgId = 9000 // 请求观看(服务端发 biz_id)
	MsgId_S2C_AD_REQUEST MsgId = 9001
	MsgId_C2S_AD_REPORT  MsgId = 9002 // 观看完成上报(服务端向微信校验)
	MsgId_S2C_AD_REPORT  MsgId = 9003
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0:    "MSG_ID_NONE",
		1:    "C2S_HEARTBEAT",
		2:    "S2C_HEARTBEAT",
		3:    "S2C_KICK",
		1000: "C2S_LOGIN",
		1001: "S2C_LOGIN",
		1002: "C2S_CREATE_ROLE",
		1003: "S2C_CREATE_ROLE",
		1004: "S2C_ROLE_BRIEF",
		2000: "C2S_OFFLINE_REWARD_QUERY",
		2001: "S2C_OFFLINE_REWARD_QUERY",
		2002: "C2S_OFFLINE_REWARD_CLAIM",
		2003: "S2C_OFFLINE_REWARD_CLAIM",
		2004: "C2S_HANG_REWARD_QUERY",
		2005: "S2C_HANG_REWARD_QUERY",
		2006: "C2S_HANG_REWARD_CLAIM",
		2007: "S2C_HANG_REWARD_CLAIM",
		3000: "C2S_START_STAGE",
		3001: "S2C_START_STAGE",
		3002: "C2S_SWEEP_STAGE",
		3003: "S2C_SWEEP_STAGE",
		4000: "C2S_EQUIP_LIST",
		4001: "S2C_EQUIP_LIST",
		4002: "C2S_EQUIP_WEAR",
		4003: "S2C_EQUIP_WEAR",
		4004: "C2S_EQUIP_STRENGTHEN",
		4005: "S2C_EQUIP_STRENGTHEN",
		4006: "C2S_EQUIP_REFINE",
		4007: "S2C_EQUIP_REFINE",
		4008: "C2S_EQUIP_DECOMPOSE",
		4009: "S2C_EQUIP_DECOMPOSE",
		5000: "C2S_PET_LIST",
		5001: "S2C_PET_LIST",
		5002: "C2S_PET_SET_COMBAT",
		5003: "S2C_PET_SET_COMBAT",
		5004: "C2S_PET_UPGRADE",
		5005: "S2C_PET_UPGRADE",
		5006: "C2S_PET_EVOLVE",
		5007: "S2C_PET_EVOLVE",
		6000: "C2S_BAG_LIST",
		6001: "S2C_BAG_LIST",
		6002: "C2S_BAG_USE_ITEM",
		6003: "S2C_BAG_USE_ITEM",
		7000: "C2S_MAIL_LIST",
		7001: "S2C_MAIL_LIST",
		7002: "C2S_MAIL_READ",
		7003: "S2C_MAIL_READ",
		7004: "C2S_MAIL_CLAIM",
		7005: "S2C_MAIL_CLAIM",
		8000: "C2S_RANK_QUERY",
		8001: "S2C_RANK_QUERY",
		9000: "C2S_AD_REQUEST",
		9001: "S2C_AD_REQUEST",
		9002: "C2S_AD_REPORT",
		9003: "S2C_AD_REPORT",
	}
	MsgId_value = map[string]int32{
		"MSG_ID_NONE":              0,
		"C2S_HEARTBEAT":            1,
		"S2C_HEARTBEAT":            2,
		"S2C_KICK":                 3,
		"C2S_LOGIN":                1000,
		"S2C_LOGIN":                1001,
		"C2S_CREATE_ROLE":          1002,
		"S2C_CREATE_ROLE":          1003,
		"S2C_ROLE_BRIEF":           1004,
		"C2S_OFFLINE_REWARD_QUERY": 2000,
		"S2C_OFFLINE_REWARD_QUERY": 2001,
		"C2S_OFFLINE_REWARD_CLAIM": 2002,
		"S2C_OFFLINE_REWARD_CLAIM": 2003,
		"C2S_HANG_REWARD_QUERY":    2004,
		"S2C_HANG_REWARD_QUERY":    2005,
		"C2S_HANG_REWARD_CLAIM":    2006,
		"S2C_HANG_REWARD_CLAIM":    2007,
		"C2S_START_STAGE":          3000,
		"S2C_START_STAGE":          3001,
		"C2S_SWEEP_STAGE":          3002,
		"S2C_SWEEP_STAGE":          3003,
		"C2S_EQUIP_LIST":           4000,
		"S2C_EQUIP_LIST":           4001,
		"C2S_EQUIP_WEAR":           4002,
		"S2C_EQUIP_WEAR":           4003,
		"C2S_EQUIP_STRENGTHEN":     4004,
		"S2C_EQUIP_STRENGTHEN":     4005,
		"C2S_EQUIP_REFINE":         4006,
		"S2C_EQUIP_REFINE":         4007,
		"C2S_EQUIP_DECOMPOSE":      4008,
		"S2C_EQUIP_DECOMPOSE":      4009,
		"C2S_PET_LIST":             5000,
		"S2C_PET_LIST":             5001,
		"C2S_PET_SET_COMBAT":       5002,
		"S2C_PET_SET_COMBAT":       5003,
		"C2S_PET_UPGRADE":          5004,
		"S2C_PET_UPGRADE":          5005,
		"C2S_PET_EVOLVE":           5006,
		"S2C_PET_EVOLVE":           5007,
		"C2S_BAG_LIST":             6000,
		"S2C_BAG_LIST":             6001,
		"C2S_BAG_USE_ITEM":         6002,
		"S2C_BAG_USE_ITEM":         6003,
		"C2S_MAIL_LIST":            7000,
		"S2C_MAIL_LIST":            7001,
		"C2S_MAIL_READ":            7002,
		"S2C_MAIL_READ":            7003,
		"C2S_MAIL_CLAIM":           7004,
		"S2C_MAIL_CLAIM":           7005,
		"C2S_RANK_QUERY":           8000,
		"S2C_RANK_QUERY":           8001,
		"C2S_AD_REQUEST":           9000,
		"S2C_AD_REQUEST":           9001,
		"C2S_AD_REPORT":            9002,
		"S2C_AD_REPORT":            9003,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// 通用响应头（嵌入每个 S2C 消息的第一个字段）
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=chenxiao.common.ErrorCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"` // 人类可读提示，仅用于日志/调试，正式展示由客户端本地化
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *Result) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 属性键值对（属性 ID 由配置表定义）
type AttrPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttrId        int32                  `protobuf:"varint,1,opt,name=attr_id,json=attrId,proto3" json:"attr_id,omitempty"` // 属性 ID
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`                 // 数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttrPair) Reset() {
	*x = AttrPair{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttrPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrPair) ProtoMessage() {}

func (x *AttrPair) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrPair.ProtoReflect.Descriptor instead.
func (*AttrPair) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *AttrPair) GetAttrId() int32 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *AttrPair) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 货币/物品奖励条目
// item_id = 1 表示铜钱，2 表示修为，其余为物品配置 ID
type RewardItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardItem) Reset() {
	*x = RewardItem{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardItem) ProtoMessage() {}

func (x *RewardItem) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardItem.ProtoReflect.Descriptor instead.
func (*RewardItem) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *RewardItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *RewardItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 装备随机词条（概率公示页引用同一配置表，保证一致）
type EquipAffix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffixId       int32                  `protobuf:"varint,1,opt,name=affix_id,json=affixId,proto3" json:"affix_id,omitempty"` // 词条 ID
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`                    // 数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipAffix) Reset() {
	*x = EquipAffix{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipAffix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipAffix) ProtoMessage() {}

func (x *EquipAffix) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipAffix.ProtoReflect.Descriptor instead.
func (*EquipAffix) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *EquipAffix) GetAffixId() int32 {
	if x != nil {
		return x.AffixId
	}
	return 0
}

func (x *EquipAffix) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 心跳
type C2SHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"` // 客户端时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SHeartbeat) Reset() {
	*x = C2SHeartbeat{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SHeartbeat) ProtoMessage() {}

func (x *C2SHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SHeartbeat.ProtoReflect.Descriptor instead.
func (*C2SHeartbeat) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *C2SHeartbeat) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type S2CHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTs      int64                  `protobuf:"varint,1,opt,name=server_ts,json=serverTs,proto3" json:"server_ts,omitempty"` // 服务端时间戳（用于客户端校时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CHeartbeat) Reset() {
	*x = S2CHeartbeat{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CHeartbeat) ProtoMessage() {}

func (x *S2CHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CHeartbeat.ProtoReflect.Descriptor instead.
func (*S2CHeartbeat) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *S2CHeartbeat) GetServerTs() int64 {
	if x != nil {
		return x.ServerTs
	}
	return 0
}

// 被踢下线（顶号/封禁/维护）
type S2CKick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        ErrorCode              `protobuf:"varint,1,opt,name=reason,proto3,enum=chenxiao.common.ErrorCode" json:"reason,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CKick) Reset() {
	*x = S2CKick{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CKick) ProtoMessage() {}

func (x *S2CKick) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CKick.ProtoReflect.Descriptor instead.
func (*S2CKick) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *S2CKick) GetReason() ErrorCode {
	if x != nil {
		return x.Reason
	}
	return ErrorCode_OK
}

func (x *S2CKick) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x0fchenxiao.common\"J\n" +
	"\x06Result\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.chenxiao.common.ErrorCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"9\n" +
	"\bAttrPair\x12\x17\n" +
	"\aattr_id\x18\x01 \x01(\x05R\x06attrId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\";\n" +
	"\n" +
	"RewardItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"=\n" +
	"\n" +
	"EquipAffix\x12\x19\n" +
	"\baffix_id\x18\x01 \x01(\x05R\aaffixId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"\x1e\n" +
	"\fC2SHeartbeat\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\"+\n" +
	"\fS2CHeartbeat\x12\x1b\n" +
	"\tserver_ts\x18\x01 \x01(\x03R\bserverTs\"O\n" +
	"\aS2CKick\x122\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1a.chenxiao.common.ErrorCodeR\x06reason\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg*\xec\x04\n" +
	"\tErrorCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x10\n" +
	"\fERR_INTERNAL\x10\x01\x12\x15\n" +
	"\x11ERR_INVALID_PARAM\x10\x02\x12\x11\n" +
	"\rERR_NOT_LOGIN\x10\x03\x12\x15\n" +
	"\x11ERR_TOKEN_EXPIRED\x10\x04\x12\x0e\n" +
	"\n" +
	"ERR_KICKED\x10\x05\x12\x13\n" +
	"\x0fERR_MAINTENANCE\x10\x06\x12\x12\n" +
	"\x0eERR_RATE_LIMIT\x10\a\x12\x1b\n" +
	"\x16ERR_LOGIN_CODE_INVALID\x10\xe9\a\x12\x14\n" +
	"\x0fERR_ROLE_EXISTS\x10\xea\a\x12\x18\n" +
	"\x13ERR_ROLE_NOT_EXISTS\x10\xeb\a\x12\x15\n" +
	"\x10ERR_NAME_INVALID\x10\xec\a\x12\x1a\n" +
	"\x15ERR_COPPER_NOT_ENOUGH\x10\xd1\x0f\x12\x1c\n" +
	"\x17ERR_MATERIAL_NOT_ENOUGH\x10\xd2\x0f\x12\x18\n" +
	"\x13ERR_EQUIP_NOT_FOUND\x10\xb9\x17\x12\x1a\n" +
	"\x15ERR_EQUIP_POS_INVALID\x10\xba\x17\x12\x1d\n" +
	"\x18ERR_STRENGTHEN_LEVEL_MAX\x10\xbb\x17\x12\x16\n" +
	"\x11ERR_PET_NOT_FOUND\x10\xa1\x1f\x12\x10\n" +
	"\vERR_PET_MAX\x10\xa2\x1f\x12\x15\n" +
	"\x10ERR_STAGE_LOCKED\x10\x89'\x12\x1a\n" +
	"\x15ERR_STAGE_TIMES_LIMIT\x10\x8a'\x12\x17\n" +
	"\x12ERR_MAIL_NOT_FOUND\x10\xf1.\x12\x1d\n" +
	"\x18ERR_MAIL_ALREADY_CLAIMED\x10\xf2.\x12\x19\n" +
	"\x14ERR_AD_NOT_COMPLETED\x10\xd96\x12\x11\n" +
	"\fERR_AD_LIMIT\x10\xda6\x12\x15\n" +
	"\x10ERR_AD_DUPLICATE\x10\xdb6*\xd5\t\n" +
	"\x05MsgId\x12\x0f\n" +
	"\vMSG_ID_NONE\x10\x00\x12\x11\n" +
	"\rC2S_HEARTBEAT\x10\x01\x12\x11\n" +
	"\rS2C_HEARTBEAT\x10\x02\x12\f\n" +
	"\bS2C_KICK\x10\x03\x12\x0e\n" +
	"\tC2S_LOGIN\x10\xe8\a\x12\x0e\n" +
	"\tS2C_LOGIN\x10\xe9\a\x12\x14\n" +
	"\x0fC2S_CREATE_ROLE\x10\xea\a\x12\x14\n" +
	"\x0fS2C_CREATE_ROLE\x10\xeb\a\x12\x13\n" +
	"\x0eS2C_ROLE_BRIEF\x10\xec\a\x12\x1d\n" +
	"\x18C2S_OFFLINE_REWARD_QUERY\x10\xd0\x0f\x12\x1d\n" +
	"\x18S2C_OFFLINE_REWARD_QUERY\x10\xd1\x0f\x12\x1d\n" +
	"\x18C2S_OFFLINE_REWARD_CLAIM\x10\xd2\x0f\x12\x1d\n" +
	"\x18S2C_OFFLINE_REWARD_CLAIM\x10\xd3\x0f\x12\x1a\n" +
	"\x15C2S_HANG_REWARD_QUERY\x10\xd4\x0f\x12\x1a\n" +
	"\x15S2C_HANG_REWARD_QUERY\x10\xd5\x0f\x12\x1a\n" +
	"\x15C2S_HANG_REWARD_CLAIM\x10\xd6\x0f\x12\x1a\n" +
	"\x15S2C_HANG_REWARD_CLAIM\x10\xd7\x0f\x12\x14\n" +
	"\x0fC2S_START_STAGE\x10\xb8\x17\x12\x14\n" +
	"\x0fS2C_START_STAGE\x10\xb9\x17\x12\x14\n" +
	"\x0fC2S_SWEEP_STAGE\x10\xba\x17\x12\x14\n" +
	"\x0fS2C_SWEEP_STAGE\x10\xbb\x17\x12\x13\n" +
	"\x0eC2S_EQUIP_LIST\x10\xa0\x1f\x12\x13\n" +
	"\x0eS2C_EQUIP_LIST\x10\xa1\x1f\x12\x13\n" +
	"\x0eC2S_EQUIP_WEAR\x10\xa2\x1f\x12\x13\n" +
	"\x0eS2C_EQUIP_WEAR\x10\xa3\x1f\x12\x19\n" +
	"\x14C2S_EQUIP_STRENGTHEN\x10\xa4\x1f\x12\x19\n" +
	"\x14S2C_EQUIP_STRENGTHEN\x10\xa5\x1f\x12\x15\n" +
	"\x10C2S_EQUIP_REFINE\x10\xa6\x1f\x12\x15\n" +
	"\x10S2C_EQUIP_REFINE\x10\xa7\x1f\x12\x18\n" +
	"\x13C2S_EQUIP_DECOMPOSE\x10\xa8\x1f\x12\x18\n" +
	"\x13S2C_EQUIP_DECOMPOSE\x10\xa9\x1f\x12\x11\n" +
	"\fC2S_PET_LIST\x10\x88'\x12\x11\n" +
	"\fS2C_PET_LIST\x10\x89'\x12\x17\n" +
	"\x12C2S_PET_SET_COMBAT\x10\x8a'\x12\x17\n" +
	"\x12S2C_PET_SET_COMBAT\x10\x8b'\x12\x14\n" +
	"\x0fC2S_PET_UPGRADE\x10\x8c'\x12\x14\n" +
	"\x0fS2C_PET_UPGRADE\x10\x8d'\x12\x13\n" +
	"\x0eC2S_PET_EVOLVE\x10\x8e'\x12\x13\n" +
	"\x0eS2C_PET_EVOLVE\x10\x8f'\x12\x11\n" +
	"\fC2S_BAG_LIST\x10\xf0.\x12\x11\n" +
	"\fS2C_BAG_LIST\x10\xf1.\x12\x15\n" +
	"\x10C2S_BAG_USE_ITEM\x10\xf2.\x12\x15\n" +
	"\x10S2C_BAG_USE_ITEM\x10\xf3.\x12\x12\n" +
	"\rC2S_MAIL_LIST\x10\xd86\x12\x12\n" +
	"\rS2C_MAIL_LIST\x10\xd96\x12\x12\n" +
	"\rC2S_MAIL_READ\x10\xda6\x12\x12\n" +
	"\rS2C_MAIL_READ\x10\xdb6\x12\x13\n" +
	"\x0eC2S_MAIL_CLAIM\x10\xdc6\x12\x13\n" +
	"\x0eS2C_MAIL_CLAIM\x10\xdd6\x12\x13\n" +
	"\x0eC2S_RANK_QUERY\x10\xc0>\x12\x13\n" +
	"\x0eS2C_RANK_QUERY\x10\xc1>\x12\x13\n" +
	"\x0eC2S_AD_REQUEST\x10\xa8F\x12\x13\n" +
	"\x0eS2C_AD_REQUEST\x10\xa9F\x12\x12\n" +
	"\rC2S_AD_REPORT\x10\xaaF\x12\x12\n" +
	"\rS2C_AD_REPORT\x10\xabFB\x1eZ\x1cchenxiao/proto/common;commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_proto_goTypes = []any{
	(ErrorCode)(0),       // 0: chenxiao.common.ErrorCode
	(MsgId)(0),           // 1: chenxiao.common.MsgId
	(*Result)(nil),       // 2: chenxiao.common.Result
	(*AttrPair)(nil),     // 3: chenxiao.common.AttrPair
	(*RewardItem)(nil),   // 4: chenxiao.common.RewardItem
	(*EquipAffix)(nil),   // 5: chenxiao.common.EquipAffix
	(*C2SHeartbeat)(nil), // 6: chenxiao.common.C2SHeartbeat
	(*S2CHeartbeat)(nil), // 7: chenxiao.common.S2CHeartbeat
	(*S2CKick)(nil),      // 8: chenxiao.common.S2CKick
}
var file_common_proto_depIdxs = []int32{
	0, // 0: chenxiao.common.Result.code:type_name -> chenxiao.common.ErrorCode
	0, // 1: chenxiao.common.S2CKick.reason:type_name -> chenxiao.common.ErrorCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
