// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: dungeon.proto

package dungeon

import (
	common "chenxiao/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 出战单位
type CombatUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          int32                  `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`                         // 1=角色 2=灵宠
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                           // 角色=player_id；灵宠=pet 实例 uid
	ConfigId      int32                  `protobuf:"varint,3,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"` // 角色=1；灵宠=pet 配置 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatUnit) Reset() {
	*x = CombatUnit{}
	mi := &file_dungeon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatUnit) ProtoMessage() {}

func (x *CombatUnit) ProtoReflect() protoreflect.Message {
	mi := &file_dungeon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatUnit.ProtoReflect.Descriptor instead.
func (*CombatUnit) Descriptor() ([]byte, []int) {
	return file_dungeon_proto_rawDescGZIP(), []int{0}
}

func (x *CombatUnit) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *CombatUnit) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CombatUnit) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

// 开始战斗
type C2SStartStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageType     int32                  `protobuf:"varint,1,opt,name=stage_type,json=stageType,proto3" json:"stage_type,omitempty"` // 1=普通 2=精英 3=BOSS
	StageId       int32                  `protobuf:"varint,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`       // 关卡配置 ID
	Team          []*CombatUnit          `protobuf:"bytes,3,rep,name=team,proto3" json:"team,omitempty"`                             // 出战阵容（服务端校验合法性）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SStartStage) Reset() {
	*x = C2SStartStage{}
	mi := &file_dungeon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SStartStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SStartStage) ProtoMessage() {}

func (x *C2SStartStage) ProtoReflect() protoreflect.Message {
	mi := &file_dungeon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SStartStage.ProtoReflect.Descriptor instead.
func (*C2SStartStage) Descriptor() ([]byte, []int) {
	return file_dungeon_proto_rawDescGZIP(), []int{1}
}

func (x *C2SStartStage) GetStageType() int32 {
	if x != nil {
		return x.StageType
	}
	return 0
}

func (x *C2SStartStage) GetStageId() int32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *C2SStartStage) GetTeam() []*CombatUnit {
	if x != nil {
		return x.Team
	}
	return nil
}

// 回合内一次行动
type BattleAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttackerUid   int64                  `protobuf:"varint,1,opt,name=attacker_uid,json=attackerUid,proto3" json:"attacker_uid,omitempty"`    // 攻击方 uid
	AttackerKind  int32                  `protobuf:"varint,2,opt,name=attacker_kind,json=attackerKind,proto3" json:"attacker_kind,omitempty"` // 攻击方 kind（1=角色 2=灵宠 3=怪物）
	TargetUid     int64                  `protobuf:"varint,3,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`          // 受击方 uid
	TargetKind    int32                  `protobuf:"varint,4,opt,name=target_kind,json=targetKind,proto3" json:"target_kind,omitempty"`       // 受击方 kind
	SkillId       int32                  `protobuf:"varint,5,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`                // 技能配置 ID
	Damage        int64                  `protobuf:"varint,6,opt,name=damage,proto3" json:"damage,omitempty"`                                 // 伤害
	Heal          int64                  `protobuf:"varint,7,opt,name=heal,proto3" json:"heal,omitempty"`                                     // 治疗
	IsCrit        bool                   `protobuf:"varint,8,opt,name=is_crit,json=isCrit,proto3" json:"is_crit,omitempty"`                   // 是否暴击
	IsDodge       bool                   `protobuf:"varint,9,opt,name=is_dodge,json=isDodge,proto3" json:"is_dodge,omitempty"`                // 是否闪避
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleAction) Reset() {
	*x = BattleAction{}
	mi := &file_dungeon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleAction) ProtoMessage() {}

func (x *BattleAction) ProtoReflect() protoreflect.Message {
	mi := &file_dungeon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleAction.ProtoReflect.Descriptor instead.
func (*BattleAction) Descriptor() ([]byte, []int) {
	return file_dungeon_proto_rawDescGZIP(), []int{2}
}

func (x *BattleAction) GetAttackerUid() int64 {
	if x != nil {
		return x.AttackerUid
	}
	return 0
}

func (x *BattleAction) GetAttackerKind() int32 {
	if x != nil {
		return x.AttackerKind
	}
	return 0
}

func (x *BattleAction) GetTargetUid() int64 {
	if x != nil {
		return x.TargetUid
	}
	return 0
}

func (x *BattleAction) GetTargetKind() int32 {
	if x != nil {
		return x.TargetKind
	}
	return 0
}

func (x *BattleAction) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *BattleAction) GetDamage() int64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *BattleAction) GetHeal() int64 {
	if x != nil {
		return x.Heal
	}
	return 0
}

func (x *BattleAction) GetIsCrit() bool {
	if x != nil {
		return x.IsCrit
	}
	return false
}

func (x *BattleAction) GetIsDodge() bool {
	if x != nil {
		return x.IsDodge
	}
	return false
}

// 一个回合（含双方多次行动）
type BattleRound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Actions       []*BattleAction        `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleRound) Reset() {
	*x = BattleRound{}
	mi := &file_dungeon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRound) ProtoMessage() {}

func (x *BattleRound) ProtoReflect() protoreflect.Message {
	mi := &file_dungeon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRound.ProtoReflect.Descriptor instead.
func (*BattleRound) Descriptor() ([]byte, []int) {
	return file_dungeon_proto_rawDescGZIP(), []int{3}
}

func (x *BattleRound) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *BattleRound) GetActions() []*BattleAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

// 装备掉落
type EquipDrop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipUid      int64                  `protobuf:"varint,1,opt,name=equip_uid,json=equipUid,proto3" json:"equip_uid,omitempty"`
	EquipId       int32                  `protobuf:"varint,2,opt,name=equip_id,json=equipId,proto3" json:"equip_id,omitempty"`
	Pos           int32                  `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`        // 部位
	Affixes       []*common.EquipAffix   `protobuf:"bytes,4,rep,name=affixes,proto3" json:"affixes,omitempty"` // 随机词条
	Score         int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipDrop) Reset() {
	*x = EquipDrop{}
	mi := &file_dungeon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipDrop) ProtoMessage() {}

func (x *EquipDrop) ProtoReflect() protoreflect.Message {
	mi := &file_dungeon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipDrop.ProtoReflect.Descriptor instead.
func (*EquipDrop) Descriptor() ([]byte, []int) {
	return file_dungeon_proto_rawDescGZIP(), []int{4}
}

func (x *EquipDrop) GetEquipUid() int64 {
	if x != nil {
		return x.EquipUid
	}
	return 0
}

func (x *EquipDrop) GetEquipId() int32 {
	if x != nil {
		return x.EquipId
	}
	return 0
}

func (x *EquipDrop) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *EquipDrop) GetAffixes() []*common.EquipAffix {
	if x != nil {
		return x.Affixes
	}
	return nil
}

func (x *EquipDrop) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 灵宠掉落
type PetDrop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetUid        int64                  `protobuf:"varint,1,opt,name=pet_uid,json=petUid,proto3" json:"pet_uid,omitempty"`
	PetId         int32                  `protobuf:"varint,2,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetDrop) Reset() {
	*x = PetDrop{}
	mi := &file_dungeon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetDrop) ProtoMessage() {}

func (x *PetDrop) ProtoReflect() protoreflect.Message {
	mi := &file_dungeon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetDrop.ProtoReflect.Descriptor instead.
func (*PetDrop) Descriptor() ([]byte, []int) {
	return file_dungeon_proto_rawDescGZIP(), []int{5}
}

func (x *PetDrop) GetPetUid() int64 {
	if x != nil {
		return x.PetUid
	}
	return 0
}

func (x *PetDrop) GetPetId() int32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

// 战斗结果
type S2CStartStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Win           bool                   `protobuf:"varint,2,opt,name=win,proto3" json:"win,omitempty"`
	Star          int32                  `protobuf:"varint,3,opt,name=star,proto3" json:"star,omitempty"`                               // 1-3 星
	Rounds        []*BattleRound         `protobuf:"bytes,4,rep,name=rounds,proto3" json:"rounds,omitempty"`                            // 回合序列（表现回放）
	Rewards       []*common.RewardItem   `protobuf:"bytes,5,rep,name=rewards,proto3" json:"rewards,omitempty"`                          // 货币/材料奖励
	Equips        []*EquipDrop           `protobuf:"bytes,6,rep,name=equips,proto3" json:"equips,omitempty"`                            // 装备掉落
	Pets          []*PetDrop             `protobuf:"bytes,7,rep,name=pets,proto3" json:"pets,omitempty"`                                // 灵宠掉落
	ClearTimes    int32                  `protobuf:"varint,8,opt,name=clear_times,json=clearTimes,proto3" json:"clear_times,omitempty"` // 本关累计通关次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CStartStage) Reset() {
	*x = S2CStartStage{}
	mi := &file_dungeon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CStartStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CStartStage) ProtoMessage() {}

func (x *S2CStartStage) ProtoReflect() protoreflect.Message {
	mi := &file_dungeon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CStartStage.ProtoReflect.Descriptor instead.
func (*S2CStartStage) Descriptor() ([]byte, []int) {
	return file_dungeon_proto_rawDescGZIP(), []int{6}
}

func (x *S2CStartStage) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CStartStage) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *S2CStartStage) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *S2CStartStage) GetRounds() []*BattleRound {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *S2CStartStage) GetRewards() []*common.RewardItem {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *S2CStartStage) GetEquips() []*EquipDrop {
	if x != nil {
		return x.Equips
	}
	return nil
}

func (x *S2CStartStage) GetPets() []*PetDrop {
	if x != nil {
		return x.Pets
	}
	return nil
}

func (x *S2CStartStage) GetClearTimes() int32 {
	if x != nil {
		return x.ClearTimes
	}
	return 0
}

// 扫荡（快速通关，无需回放）
type C2SSweepStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageType     int32                  `protobuf:"varint,1,opt,name=stage_type,json=stageType,proto3" json:"stage_type,omitempty"`
	StageId       int32                  `protobuf:"varint,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	Times         int32                  `protobuf:"varint,3,opt,name=times,proto3" json:"times,omitempty"` // 扫荡次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SSweepStage) Reset() {
	*x = C2SSweepStage{}
	mi := &file_dungeon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SSweepStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SSweepStage) ProtoMessage() {}

func (x *C2SSweepStage) ProtoReflect() protoreflect.Message {
	mi := &file_dungeon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SSweepStage.ProtoReflect.Descriptor instead.
func (*C2SSweepStage) Descriptor() ([]byte, []int) {
	return file_dungeon_proto_rawDescGZIP(), []int{7}
}

func (x *C2SSweepStage) GetStageType() int32 {
	if x != nil {
		return x.StageType
	}
	return 0
}

func (x *C2SSweepStage) GetStageId() int32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *C2SSweepStage) GetTimes() int32 {
	if x != nil {
		return x.Times
	}
	return 0
}

type S2CSweepStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Rewards       []*common.RewardItem   `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"`
	Equips        []*EquipDrop           `protobuf:"bytes,3,rep,name=equips,proto3" json:"equips,omitempty"`
	Pets          []*PetDrop             `protobuf:"bytes,4,rep,name=pets,proto3" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CSweepStage) Reset() {
	*x = S2CSweepStage{}
	mi := &file_dungeon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CSweepStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CSweepStage) ProtoMessage() {}

func (x *S2CSweepStage) ProtoReflect() protoreflect.Message {
	mi := &file_dungeon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CSweepStage.ProtoReflect.Descriptor instead.
func (*S2CSweepStage) Descriptor() ([]byte, []int) {
	return file_dungeon_proto_rawDescGZIP(), []int{8}
}

func (x *S2CSweepStage) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CSweepStage) GetRewards() []*common.RewardItem {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *S2CSweepStage) GetEquips() []*EquipDrop {
	if x != nil {
		return x.Equips
	}
	return nil
}

func (x *S2CSweepStage) GetPets() []*PetDrop {
	if x != nil {
		return x.Pets
	}
	return nil
}

var File_dungeon_proto protoreflect.FileDescriptor

const file_dungeon_proto_rawDesc = "" +
	"\n" +
	"\rdungeon.proto\x12\x10chenxiao.dungeon\x1a\fcommon.proto\"O\n" +
	"\n" +
	"CombatUnit\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\x05R\x04kind\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x1b\n" +
	"\tconfig_id\x18\x03 \x01(\x05R\bconfigId\"{\n" +
	"\rC2SStartStage\x12\x1d\n" +
	"\n" +
	"stage_type\x18\x01 \x01(\x05R\tstageType\x12\x19\n" +
	"\bstage_id\x18\x02 \x01(\x05R\astageId\x120\n" +
	"\x04team\x18\x03 \x03(\v2\x1c.chenxiao.dungeon.CombatUnitR\x04team\"\x91\x02\n" +
	"\fBattleAction\x12!\n" +
	"\fattacker_uid\x18\x01 \x01(\x03R\vattackerUid\x12#\n" +
	"\rattacker_kind\x18\x02 \x01(\x05R\fattackerKind\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x03 \x01(\x03R\ttargetUid\x12\x1f\n" +
	"\vtarget_kind\x18\x04 \x01(\x05R\n" +
	"targetKind\x12\x19\n" +
	"\bskill_id\x18\x05 \x01(\x05R\askillId\x12\x16\n" +
	"\x06damage\x18\x06 \x01(\x03R\x06damage\x12\x12\n" +
	"\x04heal\x18\a \x01(\x03R\x04heal\x12\x17\n" +
	"\ais_crit\x18\b \x01(\bR\x06isCrit\x12\x19\n" +
	"\bis_dodge\x18\t \x01(\bR\aisDodge\"]\n" +
	"\vBattleRound\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x128\n" +
	"\aactions\x18\x02 \x03(\v2\x1e.chenxiao.dungeon.BattleActionR\aactions\"\xa2\x01\n" +
	"\tEquipDrop\x12\x1b\n" +
	"\tequip_uid\x18\x01 \x01(\x03R\bequipUid\x12\x19\n" +
	"\bequip_id\x18\x02 \x01(\x05R\aequipId\x12\x10\n" +
	"\x03pos\x18\x03 \x01(\x05R\x03pos\x125\n" +
	"\aaffixes\x18\x04 \x03(\v2\x1b.chenxiao.common.EquipAffixR\aaffixes\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\"9\n" +
	"\aPetDrop\x12\x17\n" +
	"\apet_uid\x18\x01 \x01(\x03R\x06petUid\x12\x15\n" +
	"\x06pet_id\x18\x02 \x01(\x05R\x05petId\"\xd9\x02\n" +
	"\rS2CStartStage\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12\x10\n" +
	"\x03win\x18\x02 \x01(\bR\x03win\x12\x12\n" +
	"\x04star\x18\x03 \x01(\x05R\x04star\x125\n" +
	"\x06rounds\x18\x04 \x03(\v2\x1d.chenxiao.dungeon.BattleRoundR\x06rounds\x125\n" +
	"\arewards\x18\x05 \x03(\v2\x1b.chenxiao.common.RewardItemR\arewards\x123\n" +
	"\x06equips\x18\x06 \x03(\v2\x1b.chenxiao.dungeon.EquipDropR\x06equips\x12-\n" +
	"\x04pets\x18\a \x03(\v2\x19.chenxiao.dungeon.PetDropR\x04pets\x12\x1f\n" +
	"\vclear_times\x18\b \x01(\x05R\n" +
	"clearTimes\"_\n" +
	"\rC2SSweepStage\x12\x1d\n" +
	"\n" +
	"stage_type\x18\x01 \x01(\x05R\tstageType\x12\x19\n" +
	"\bstage_id\x18\x02 \x01(\x05R\astageId\x12\x14\n" +
	"\x05times\x18\x03 \x01(\x05R\x05times\"\xdb\x01\n" +
	"\rS2CSweepStage\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x125\n" +
	"\arewards\x18\x02 \x03(\v2\x1b.chenxiao.common.RewardItemR\arewards\x123\n" +
	"\x06equips\x18\x03 \x03(\v2\x1b.chenxiao.dungeon.EquipDropR\x06equips\x12-\n" +
	"\x04pets\x18\x04 \x03(\v2\x19.chenxiao.dungeon.PetDropR\x04petsB Z\x1echenxiao/proto/dungeon;dungeonb\x06proto3"

var (
	file_dungeon_proto_rawDescOnce sync.Once
	file_dungeon_proto_rawDescData []byte
)

func file_dungeon_proto_rawDescGZIP() []byte {
	file_dungeon_proto_rawDescOnce.Do(func() {
		file_dungeon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dungeon_proto_rawDesc), len(file_dungeon_proto_rawDesc)))
	})
	return file_dungeon_proto_rawDescData
}

var file_dungeon_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_dungeon_proto_goTypes = []any{
	(*CombatUnit)(nil),        // 0: chenxiao.dungeon.CombatUnit
	(*C2SStartStage)(nil),     // 1: chenxiao.dungeon.C2SStartStage
	(*BattleAction)(nil),      // 2: chenxiao.dungeon.BattleAction
	(*BattleRound)(nil),       // 3: chenxiao.dungeon.BattleRound
	(*EquipDrop)(nil),         // 4: chenxiao.dungeon.EquipDrop
	(*PetDrop)(nil),           // 5: chenxiao.dungeon.PetDrop
	(*S2CStartStage)(nil),     // 6: chenxiao.dungeon.S2CStartStage
	(*C2SSweepStage)(nil),     // 7: chenxiao.dungeon.C2SSweepStage
	(*S2CSweepStage)(nil),     // 8: chenxiao.dungeon.S2CSweepStage
	(*common.EquipAffix)(nil), // 9: chenxiao.common.EquipAffix
	(*common.Result)(nil),     // 10: chenxiao.common.Result
	(*common.RewardItem)(nil), // 11: chenxiao.common.RewardItem
}
var file_dungeon_proto_depIdxs = []int32{
	0,  // 0: chenxiao.dungeon.C2SStartStage.team:type_name -> chenxiao.dungeon.CombatUnit
	2,  // 1: chenxiao.dungeon.BattleRound.actions:type_name -> chenxiao.dungeon.BattleAction
	9,  // 2: chenxiao.dungeon.EquipDrop.affixes:type_name -> chenxiao.common.EquipAffix
	10, // 3: chenxiao.dungeon.S2CStartStage.result:type_name -> chenxiao.common.Result
	3,  // 4: chenxiao.dungeon.S2CStartStage.rounds:type_name -> chenxiao.dungeon.BattleRound
	11, // 5: chenxiao.dungeon.S2CStartStage.rewards:type_name -> chenxiao.common.RewardItem
	4,  // 6: chenxiao.dungeon.S2CStartStage.equips:type_name -> chenxiao.dungeon.EquipDrop
	5,  // 7: chenxiao.dungeon.S2CStartStage.pets:type_name -> chenxiao.dungeon.PetDrop
	10, // 8: chenxiao.dungeon.S2CSweepStage.result:type_name -> chenxiao.common.Result
	11, // 9: chenxiao.dungeon.S2CSweepStage.rewards:type_name -> chenxiao.common.RewardItem
	4,  // 10: chenxiao.dungeon.S2CSweepStage.equips:type_name -> chenxiao.dungeon.EquipDrop
	5,  // 11: chenxiao.dungeon.S2CSweepStage.pets:type_name -> chenxiao.dungeon.PetDrop
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_dungeon_proto_init() }
func file_dungeon_proto_init() {
	if File_dungeon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dungeon_proto_rawDesc), len(file_dungeon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dungeon_proto_goTypes,
		DependencyIndexes: file_dungeon_proto_depIdxs,
		MessageInfos:      file_dungeon_proto_msgTypes,
	}.Build()
	File_dungeon_proto = out.File
	file_dungeon_proto_goTypes = nil
	file_dungeon_proto_depIdxs = nil
}
