// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: equip.proto

package equip

import (
	common "chenxiao/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 装备实例
type EquipInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EquipUid        int64                  `protobuf:"varint,1,opt,name=equip_uid,json=equipUid,proto3" json:"equip_uid,omitempty"`
	EquipId         int32                  `protobuf:"varint,2,opt,name=equip_id,json=equipId,proto3" json:"equip_id,omitempty"`
	Pos             int32                  `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`                                                // 0=背包 1..8=部位
	StrengthenLevel int32                  `protobuf:"varint,4,opt,name=strengthen_level,json=strengthenLevel,proto3" json:"strengthen_level,omitempty"` // 强化等级
	RefineLevel     int32                  `protobuf:"varint,5,opt,name=refine_level,json=refineLevel,proto3" json:"refine_level,omitempty"`             // 精炼等级
	Affixes         []*common.EquipAffix   `protobuf:"bytes,6,rep,name=affixes,proto3" json:"affixes,omitempty"`                                         // 随机词条
	Score           int32                  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`                                            // 评分
	IsLocked        bool                   `protobuf:"varint,8,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`                      // 是否锁定
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EquipInfo) Reset() {
	*x = EquipInfo{}
	mi := &file_equip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipInfo) ProtoMessage() {}

func (x *EquipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipInfo.ProtoReflect.Descriptor instead.
func (*EquipInfo) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{0}
}

func (x *EquipInfo) GetEquipUid() int64 {
	if x != nil {
		return x.EquipUid
	}
	return 0
}

func (x *EquipInfo) GetEquipId() int32 {
	if x != nil {
		return x.EquipId
	}
	return 0
}

func (x *EquipInfo) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *EquipInfo) GetStrengthenLevel() int32 {
	if x != nil {
		return x.StrengthenLevel
	}
	return 0
}

func (x *EquipInfo) GetRefineLevel() int32 {
	if x != nil {
		return x.RefineLevel
	}
	return 0
}

func (x *EquipInfo) GetAffixes() []*common.EquipAffix {
	if x != nil {
		return x.Affixes
	}
	return nil
}

func (x *EquipInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *EquipInfo) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

// 装备列表
type C2SEquipList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SEquipList) Reset() {
	*x = C2SEquipList{}
	mi := &file_equip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SEquipList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SEquipList) ProtoMessage() {}

func (x *C2SEquipList) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SEquipList.ProtoReflect.Descriptor instead.
func (*C2SEquipList) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{1}
}

type S2CEquipList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Equips        []*EquipInfo           `protobuf:"bytes,2,rep,name=equips,proto3" json:"equips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CEquipList) Reset() {
	*x = S2CEquipList{}
	mi := &file_equip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CEquipList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CEquipList) ProtoMessage() {}

func (x *S2CEquipList) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CEquipList.ProtoReflect.Descriptor instead.
func (*S2CEquipList) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{2}
}

func (x *S2CEquipList) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CEquipList) GetEquips() []*EquipInfo {
	if x != nil {
		return x.Equips
	}
	return nil
}

// 穿戴 / 脱下（target_pos = 0 表示脱下到背包）
type C2SEquipWear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipUid      int64                  `protobuf:"varint,1,opt,name=equip_uid,json=equipUid,proto3" json:"equip_uid,omitempty"`
	TargetPos     int32                  `protobuf:"varint,2,opt,name=target_pos,json=targetPos,proto3" json:"target_pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SEquipWear) Reset() {
	*x = C2SEquipWear{}
	mi := &file_equip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SEquipWear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SEquipWear) ProtoMessage() {}

func (x *C2SEquipWear) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SEquipWear.ProtoReflect.Descriptor instead.
func (*C2SEquipWear) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{3}
}

func (x *C2SEquipWear) GetEquipUid() int64 {
	if x != nil {
		return x.EquipUid
	}
	return 0
}

func (x *C2SEquipWear) GetTargetPos() int32 {
	if x != nil {
		return x.TargetPos
	}
	return 0
}

type S2CEquipWear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Changed       []*EquipInfo           `protobuf:"bytes,2,rep,name=changed,proto3" json:"changed,omitempty"` // 受影响的装备（穿/脱双方，用于 UI 刷新）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CEquipWear) Reset() {
	*x = S2CEquipWear{}
	mi := &file_equip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CEquipWear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CEquipWear) ProtoMessage() {}

func (x *S2CEquipWear) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CEquipWear.ProtoReflect.Descriptor instead.
func (*S2CEquipWear) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{4}
}

func (x *S2CEquipWear) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CEquipWear) GetChanged() []*EquipInfo {
	if x != nil {
		return x.Changed
	}
	return nil
}

// 强化
type C2SEquipStrengthen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipUid      int64                  `protobuf:"varint,1,opt,name=equip_uid,json=equipUid,proto3" json:"equip_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SEquipStrengthen) Reset() {
	*x = C2SEquipStrengthen{}
	mi := &file_equip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SEquipStrengthen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SEquipStrengthen) ProtoMessage() {}

func (x *C2SEquipStrengthen) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SEquipStrengthen.ProtoReflect.Descriptor instead.
func (*C2SEquipStrengthen) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{5}
}

func (x *C2SEquipStrengthen) GetEquipUid() int64 {
	if x != nil {
		return x.EquipUid
	}
	return 0
}

type S2CEquipStrengthen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Equip         *EquipInfo             `protobuf:"bytes,2,opt,name=equip,proto3" json:"equip,omitempty"`
	CopperCost    int64                  `protobuf:"varint,3,opt,name=copper_cost,json=copperCost,proto3" json:"copper_cost,omitempty"` // 本次消耗铜钱（展示用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CEquipStrengthen) Reset() {
	*x = S2CEquipStrengthen{}
	mi := &file_equip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CEquipStrengthen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CEquipStrengthen) ProtoMessage() {}

func (x *S2CEquipStrengthen) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CEquipStrengthen.ProtoReflect.Descriptor instead.
func (*S2CEquipStrengthen) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{6}
}

func (x *S2CEquipStrengthen) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CEquipStrengthen) GetEquip() *EquipInfo {
	if x != nil {
		return x.Equip
	}
	return nil
}

func (x *S2CEquipStrengthen) GetCopperCost() int64 {
	if x != nil {
		return x.CopperCost
	}
	return 0
}

// 精炼
type C2SEquipRefine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipUid      int64                  `protobuf:"varint,1,opt,name=equip_uid,json=equipUid,proto3" json:"equip_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SEquipRefine) Reset() {
	*x = C2SEquipRefine{}
	mi := &file_equip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SEquipRefine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SEquipRefine) ProtoMessage() {}

func (x *C2SEquipRefine) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SEquipRefine.ProtoReflect.Descriptor instead.
func (*C2SEquipRefine) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{7}
}

func (x *C2SEquipRefine) GetEquipUid() int64 {
	if x != nil {
		return x.EquipUid
	}
	return 0
}

type S2CEquipRefine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Equip         *EquipInfo             `protobuf:"bytes,2,opt,name=equip,proto3" json:"equip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CEquipRefine) Reset() {
	*x = S2CEquipRefine{}
	mi := &file_equip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CEquipRefine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CEquipRefine) ProtoMessage() {}

func (x *S2CEquipRefine) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CEquipRefine.ProtoReflect.Descriptor instead.
func (*S2CEquipRefine) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{8}
}

func (x *S2CEquipRefine) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CEquipRefine) GetEquip() *EquipInfo {
	if x != nil {
		return x.Equip
	}
	return nil
}

// 分解（换取材料）
type C2SEquipDecompose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipUids     []int64                `protobuf:"varint,1,rep,packed,name=equip_uids,json=equipUids,proto3" json:"equip_uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SEquipDecompose) Reset() {
	*x = C2SEquipDecompose{}
	mi := &file_equip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SEquipDecompose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SEquipDecompose) ProtoMessage() {}

func (x *C2SEquipDecompose) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SEquipDecompose.ProtoReflect.Descriptor instead.
func (*C2SEquipDecompose) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{9}
}

func (x *C2SEquipDecompose) GetEquipUids() []int64 {
	if x != nil {
		return x.EquipUids
	}
	return nil
}

type S2CEquipDecompose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Rewards       []*common.RewardItem   `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CEquipDecompose) Reset() {
	*x = S2CEquipDecompose{}
	mi := &file_equip_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CEquipDecompose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CEquipDecompose) ProtoMessage() {}

func (x *S2CEquipDecompose) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CEquipDecompose.ProtoReflect.Descriptor instead.
func (*S2CEquipDecompose) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{10}
}

func (x *S2CEquipDecompose) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CEquipDecompose) GetRewards() []*common.RewardItem {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_equip_proto protoreflect.FileDescriptor

const file_equip_proto_rawDesc = "" +
	"\n" +
	"\vequip.proto\x12\x0echenxiao.equip\x1a\fcommon.proto\"\x8d\x02\n" +
	"\tEquipInfo\x12\x1b\n" +
	"\tequip_uid\x18\x01 \x01(\x03R\bequipUid\x12\x19\n" +
	"\bequip_id\x18\x02 \x01(\x05R\aequipId\x12\x10\n" +
	"\x03pos\x18\x03 \x01(\x05R\x03pos\x12)\n" +
	"\x10strengthen_level\x18\x04 \x01(\x05R\x0fstrengthenLevel\x12!\n" +
	"\frefine_level\x18\x05 \x01(\x05R\vrefineLevel\x125\n" +
	"\aaffixes\x18\x06 \x03(\v2\x1b.chenxiao.common.EquipAffixR\aaffixes\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x12\x1b\n" +
	"\tis_locked\x18\b \x01(\bR\bisLocked\"\x0e\n" +
	"\fC2SEquipList\"r\n" +
	"\fS2CEquipList\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x121\n" +
	"\x06equips\x18\x02 \x03(\v2\x19.chenxiao.equip.EquipInfoR\x06equips\"J\n" +
	"\fC2SEquipWear\x12\x1b\n" +
	"\tequip_uid\x18\x01 \x01(\x03R\bequipUid\x12\x1d\n" +
	"\n" +
	"target_pos\x18\x02 \x01(\x05R\ttargetPos\"t\n" +
	"\fS2CEquipWear\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x123\n" +
	"\achanged\x18\x02 \x03(\v2\x19.chenxiao.equip.EquipInfoR\achanged\"1\n" +
	"\x12C2SEquipStrengthen\x12\x1b\n" +
	"\tequip_uid\x18\x01 \x01(\x03R\bequipUid\"\x97\x01\n" +
	"\x12S2CEquipStrengthen\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12/\n" +
	"\x05equip\x18\x02 \x01(\v2\x19.chenxiao.equip.EquipInfoR\x05equip\x12\x1f\n" +
	"\vcopper_cost\x18\x03 \x01(\x03R\n" +
	"copperCost\"-\n" +
	"\x0eC2SEquipRefine\x12\x1b\n" +
	"\tequip_uid\x18\x01 \x01(\x03R\bequipUid\"r\n" +
	"\x0eS2CEquipRefine\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12/\n" +
	"\x05equip\x18\x02 \x01(\v2\x19.chenxiao.equip.EquipInfoR\x05equip\"2\n" +
	"\x11C2SEquipDecompose\x12\x1d\n" +
	"\n" +
	"equip_uids\x18\x01 \x03(\x03R\tequipUids\"{\n" +
	"\x11S2CEquipDecompose\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x125\n" +
	"\arewards\x18\x02 \x03(\v2\x1b.chenxiao.common.RewardItemR\arewardsB\x1cZ\x1achenxiao/proto/equip;equipb\x06proto3"

var (
	file_equip_proto_rawDescOnce sync.Once
	file_equip_proto_rawDescData []byte
)

func file_equip_proto_rawDescGZIP() []byte {
	file_equip_proto_rawDescOnce.Do(func() {
		file_equip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_equip_proto_rawDesc), len(file_equip_proto_rawDesc)))
	})
	return file_equip_proto_rawDescData
}

var file_equip_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_equip_proto_goTypes = []any{
	(*EquipInfo)(nil),          // 0: chenxiao.equip.EquipInfo
	(*C2SEquipList)(nil),       // 1: chenxiao.equip.C2SEquipList
	(*S2CEquipList)(nil),       // 2: chenxiao.equip.S2CEquipList
	(*C2SEquipWear)(nil),       // 3: chenxiao.equip.C2SEquipWear
	(*S2CEquipWear)(nil),       // 4: chenxiao.equip.S2CEquipWear
	(*C2SEquipStrengthen)(nil), // 5: chenxiao.equip.C2SEquipStrengthen
	(*S2CEquipStrengthen)(nil), // 6: chenxiao.equip.S2CEquipStrengthen
	(*C2SEquipRefine)(nil),     // 7: chenxiao.equip.C2SEquipRefine
	(*S2CEquipRefine)(nil),     // 8: chenxiao.equip.S2CEquipRefine
	(*C2SEquipDecompose)(nil),  // 9: chenxiao.equip.C2SEquipDecompose
	(*S2CEquipDecompose)(nil),  // 10: chenxiao.equip.S2CEquipDecompose
	(*common.EquipAffix)(nil),  // 11: chenxiao.common.EquipAffix
	(*common.Result)(nil),      // 12: chenxiao.common.Result
	(*common.RewardItem)(nil),  // 13: chenxiao.common.RewardItem
}
var file_equip_proto_depIdxs = []int32{
	11, // 0: chenxiao.equip.EquipInfo.affixes:type_name -> chenxiao.common.EquipAffix
	12, // 1: chenxiao.equip.S2CEquipList.result:type_name -> chenxiao.common.Result
	0,  // 2: chenxiao.equip.S2CEquipList.equips:type_name -> chenxiao.equip.EquipInfo
	12, // 3: chenxiao.equip.S2CEquipWear.result:type_name -> chenxiao.common.Result
	0,  // 4: chenxiao.equip.S2CEquipWear.changed:type_name -> chenxiao.equip.EquipInfo
	12, // 5: chenxiao.equip.S2CEquipStrengthen.result:type_name -> chenxiao.common.Result
	0,  // 6: chenxiao.equip.S2CEquipStrengthen.equip:type_name -> chenxiao.equip.EquipInfo
	12, // 7: chenxiao.equip.S2CEquipRefine.result:type_name -> chenxiao.common.Result
	0,  // 8: chenxiao.equip.S2CEquipRefine.equip:type_name -> chenxiao.equip.EquipInfo
	12, // 9: chenxiao.equip.S2CEquipDecompose.result:type_name -> chenxiao.common.Result
	13, // 10: chenxiao.equip.S2CEquipDecompose.rewards:type_name -> chenxiao.common.RewardItem
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_equip_proto_init() }
func file_equip_proto_init() {
	if File_equip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_equip_proto_rawDesc), len(file_equip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_equip_proto_goTypes,
		DependencyIndexes: file_equip_proto_depIdxs,
		MessageInfos:      file_equip_proto_msgTypes,
	}.Build()
	File_equip_proto = out.File
	file_equip_proto_goTypes = nil
	file_equip_proto_depIdxs = nil
}
