// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: pet.proto

package pet

import (
	common "chenxiao/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 灵宠实例
type PetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetUid        int64                  `protobuf:"varint,1,opt,name=pet_uid,json=petUid,proto3" json:"pet_uid,omitempty"`
	PetId         int32                  `protobuf:"varint,2,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"` // 灵宠配置 ID
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Star          int32                  `protobuf:"varint,5,opt,name=star,proto3" json:"star,omitempty"`                                                                                                             // 星级（进化）
	SkillLevels   map[int32]int32        `protobuf:"bytes,6,rep,name=skill_levels,json=skillLevels,proto3" json:"skill_levels,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // skillId -> level
	IsCombat      bool                   `protobuf:"varint,7,opt,name=is_combat,json=isCombat,proto3" json:"is_combat,omitempty"`                                                                                     // 是否出战助战
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetInfo) Reset() {
	*x = PetInfo{}
	mi := &file_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetInfo) ProtoMessage() {}

func (x *PetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetInfo.ProtoReflect.Descriptor instead.
func (*PetInfo) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{0}
}

func (x *PetInfo) GetPetUid() int64 {
	if x != nil {
		return x.PetUid
	}
	return 0
}

func (x *PetInfo) GetPetId() int32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *PetInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PetInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PetInfo) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *PetInfo) GetSkillLevels() map[int32]int32 {
	if x != nil {
		return x.SkillLevels
	}
	return nil
}

func (x *PetInfo) GetIsCombat() bool {
	if x != nil {
		return x.IsCombat
	}
	return false
}

// 灵宠列表
type C2SPetList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SPetList) Reset() {
	*x = C2SPetList{}
	mi := &file_pet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SPetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SPetList) ProtoMessage() {}

func (x *C2SPetList) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SPetList.ProtoReflect.Descriptor instead.
func (*C2SPetList) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{1}
}

type S2CPetList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Pets          []*PetInfo             `protobuf:"bytes,2,rep,name=pets,proto3" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CPetList) Reset() {
	*x = S2CPetList{}
	mi := &file_pet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CPetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CPetList) ProtoMessage() {}

func (x *S2CPetList) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CPetList.ProtoReflect.Descriptor instead.
func (*S2CPetList) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{2}
}

func (x *S2CPetList) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CPetList) GetPets() []*PetInfo {
	if x != nil {
		return x.Pets
	}
	return nil
}

// 出战 / 休息
type C2SPetSetCombat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetUid        int64                  `protobuf:"varint,1,opt,name=pet_uid,json=petUid,proto3" json:"pet_uid,omitempty"`
	Combat        bool                   `protobuf:"varint,2,opt,name=combat,proto3" json:"combat,omitempty"` // true=出战 false=休息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SPetSetCombat) Reset() {
	*x = C2SPetSetCombat{}
	mi := &file_pet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SPetSetCombat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SPetSetCombat) ProtoMessage() {}

func (x *C2SPetSetCombat) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SPetSetCombat.ProtoReflect.Descriptor instead.
func (*C2SPetSetCombat) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{3}
}

func (x *C2SPetSetCombat) GetPetUid() int64 {
	if x != nil {
		return x.PetUid
	}
	return 0
}

func (x *C2SPetSetCombat) GetCombat() bool {
	if x != nil {
		return x.Combat
	}
	return false
}

type S2CPetSetCombat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Changed       []*PetInfo             `protobuf:"bytes,2,rep,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CPetSetCombat) Reset() {
	*x = S2CPetSetCombat{}
	mi := &file_pet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CPetSetCombat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CPetSetCombat) ProtoMessage() {}

func (x *S2CPetSetCombat) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CPetSetCombat.ProtoReflect.Descriptor instead.
func (*S2CPetSetCombat) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{4}
}

func (x *S2CPetSetCombat) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CPetSetCombat) GetChanged() []*PetInfo {
	if x != nil {
		return x.Changed
	}
	return nil
}

// 升级
type C2SPetUpgrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetUid        int64                  `protobuf:"varint,1,opt,name=pet_uid,json=petUid,proto3" json:"pet_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SPetUpgrade) Reset() {
	*x = C2SPetUpgrade{}
	mi := &file_pet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SPetUpgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SPetUpgrade) ProtoMessage() {}

func (x *C2SPetUpgrade) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SPetUpgrade.ProtoReflect.Descriptor instead.
func (*C2SPetUpgrade) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{5}
}

func (x *C2SPetUpgrade) GetPetUid() int64 {
	if x != nil {
		return x.PetUid
	}
	return 0
}

type S2CPetUpgrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Pet           *PetInfo               `protobuf:"bytes,2,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CPetUpgrade) Reset() {
	*x = S2CPetUpgrade{}
	mi := &file_pet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CPetUpgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CPetUpgrade) ProtoMessage() {}

func (x *S2CPetUpgrade) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CPetUpgrade.ProtoReflect.Descriptor instead.
func (*S2CPetUpgrade) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{6}
}

func (x *S2CPetUpgrade) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CPetUpgrade) GetPet() *PetInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

// 进化（升星）
type C2SPetEvolve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetUid        int64                  `protobuf:"varint,1,opt,name=pet_uid,json=petUid,proto3" json:"pet_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SPetEvolve) Reset() {
	*x = C2SPetEvolve{}
	mi := &file_pet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SPetEvolve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SPetEvolve) ProtoMessage() {}

func (x *C2SPetEvolve) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SPetEvolve.ProtoReflect.Descriptor instead.
func (*C2SPetEvolve) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{7}
}

func (x *C2SPetEvolve) GetPetUid() int64 {
	if x != nil {
		return x.PetUid
	}
	return 0
}

type S2CPetEvolve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Pet           *PetInfo               `protobuf:"bytes,2,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CPetEvolve) Reset() {
	*x = S2CPetEvolve{}
	mi := &file_pet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CPetEvolve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CPetEvolve) ProtoMessage() {}

func (x *S2CPetEvolve) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CPetEvolve.ProtoReflect.Descriptor instead.
func (*S2CPetEvolve) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{8}
}

func (x *S2CPetEvolve) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CPetEvolve) GetPet() *PetInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

var File_pet_proto protoreflect.FileDescriptor

const file_pet_proto_rawDesc = "" +
	"\n" +
	"\tpet.proto\x12\fchenxiao.pet\x1a\fcommon.proto\"\x9d\x02\n" +
	"\aPetInfo\x12\x17\n" +
	"\apet_uid\x18\x01 \x01(\x03R\x06petUid\x12\x15\n" +
	"\x06pet_id\x18\x02 \x01(\x05R\x05petId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x12\n" +
	"\x04star\x18\x05 \x01(\x05R\x04star\x12I\n" +
	"\fskill_levels\x18\x06 \x03(\v2&.chenxiao.pet.PetInfo.SkillLevelsEntryR\vskillLevels\x12\x1b\n" +
	"\tis_combat\x18\a \x01(\bR\bisCombat\x1a>\n" +
	"\x10SkillLevelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\f\n" +
	"\n" +
	"C2SPetList\"h\n" +
	"\n" +
	"S2CPetList\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12)\n" +
	"\x04pets\x18\x02 \x03(\v2\x15.chenxiao.pet.PetInfoR\x04pets\"B\n" +
	"\x0fC2SPetSetCombat\x12\x17\n" +
	"\apet_uid\x18\x01 \x01(\x03R\x06petUid\x12\x16\n" +
	"\x06combat\x18\x02 \x01(\bR\x06combat\"s\n" +
	"\x0fS2CPetSetCombat\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12/\n" +
	"\achanged\x18\x02 \x03(\v2\x15.chenxiao.pet.PetInfoR\achanged\"(\n" +
	"\rC2SPetUpgrade\x12\x17\n" +
	"\apet_uid\x18\x01 \x01(\x03R\x06petUid\"i\n" +
	"\rS2CPetUpgrade\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12'\n" +
	"\x03pet\x18\x02 \x01(\v2\x15.chenxiao.pet.PetInfoR\x03pet\"'\n" +
	"\fC2SPetEvolve\x12\x17\n" +
	"\apet_uid\x18\x01 \x01(\x03R\x06petUid\"h\n" +
	"\fS2CPetEvolve\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12'\n" +
	"\x03pet\x18\x02 \x01(\v2\x15.chenxiao.pet.PetInfoR\x03petB\x18Z\x16chenxiao/proto/pet;petb\x06proto3"

var (
	file_pet_proto_rawDescOnce sync.Once
	file_pet_proto_rawDescData []byte
)

func file_pet_proto_rawDescGZIP() []byte {
	file_pet_proto_rawDescOnce.Do(func() {
		file_pet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pet_proto_rawDesc), len(file_pet_proto_rawDesc)))
	})
	return file_pet_proto_rawDescData
}

var file_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pet_proto_goTypes = []any{
	(*PetInfo)(nil),         // 0: chenxiao.pet.PetInfo
	(*C2SPetList)(nil),      // 1: chenxiao.pet.C2SPetList
	(*S2CPetList)(nil),      // 2: chenxiao.pet.S2CPetList
	(*C2SPetSetCombat)(nil), // 3: chenxiao.pet.C2SPetSetCombat
	(*S2CPetSetCombat)(nil), // 4: chenxiao.pet.S2CPetSetCombat
	(*C2SPetUpgrade)(nil),   // 5: chenxiao.pet.C2SPetUpgrade
	(*S2CPetUpgrade)(nil),   // 6: chenxiao.pet.S2CPetUpgrade
	(*C2SPetEvolve)(nil),    // 7: chenxiao.pet.C2SPetEvolve
	(*S2CPetEvolve)(nil),    // 8: chenxiao.pet.S2CPetEvolve
	nil,                     // 9: chenxiao.pet.PetInfo.SkillLevelsEntry
	(*common.Result)(nil),   // 10: chenxiao.common.Result
}
var file_pet_proto_depIdxs = []int32{
	9,  // 0: chenxiao.pet.PetInfo.skill_levels:type_name -> chenxiao.pet.PetInfo.SkillLevelsEntry
	10, // 1: chenxiao.pet.S2CPetList.result:type_name -> chenxiao.common.Result
	0,  // 2: chenxiao.pet.S2CPetList.pets:type_name -> chenxiao.pet.PetInfo
	10, // 3: chenxiao.pet.S2CPetSetCombat.result:type_name -> chenxiao.common.Result
	0,  // 4: chenxiao.pet.S2CPetSetCombat.changed:type_name -> chenxiao.pet.PetInfo
	10, // 5: chenxiao.pet.S2CPetUpgrade.result:type_name -> chenxiao.common.Result
	0,  // 6: chenxiao.pet.S2CPetUpgrade.pet:type_name -> chenxiao.pet.PetInfo
	10, // 7: chenxiao.pet.S2CPetEvolve.result:type_name -> chenxiao.common.Result
	0,  // 8: chenxiao.pet.S2CPetEvolve.pet:type_name -> chenxiao.pet.PetInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pet_proto_init() }
func file_pet_proto_init() {
	if File_pet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pet_proto_rawDesc), len(file_pet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pet_proto_goTypes,
		DependencyIndexes: file_pet_proto_depIdxs,
		MessageInfos:      file_pet_proto_msgTypes,
	}.Build()
	File_pet_proto = out.File
	file_pet_proto_goTypes = nil
	file_pet_proto_depIdxs = nil
}
