// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: offline.proto

package offline

import (
	common "chenxiao/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 查询离线收益预览（未领取）
type C2SOfflineRewardQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SOfflineRewardQuery) Reset() {
	*x = C2SOfflineRewardQuery{}
	mi := &file_offline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SOfflineRewardQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SOfflineRewardQuery) ProtoMessage() {}

func (x *C2SOfflineRewardQuery) ProtoReflect() protoreflect.Message {
	mi := &file_offline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SOfflineRewardQuery.ProtoReflect.Descriptor instead.
func (*C2SOfflineRewardQuery) Descriptor() ([]byte, []int) {
	return file_offline_proto_rawDescGZIP(), []int{0}
}

type S2COfflineRewardQuery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Result         *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	OfflineSeconds int64                  `protobuf:"varint,2,opt,name=offline_seconds,json=offlineSeconds,proto3" json:"offline_seconds,omitempty"` // 已结算的离线时长（已封顶，如 24h）
	Rewards        []*common.RewardItem   `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards,omitempty"`                                      // 收益预览
	HangMultiplier int32                  `protobuf:"varint,4,opt,name=hang_multiplier,json=hangMultiplier,proto3" json:"hang_multiplier,omitempty"` // 当前挂机倍率（受广告加成影响）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2COfflineRewardQuery) Reset() {
	*x = S2COfflineRewardQuery{}
	mi := &file_offline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2COfflineRewardQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2COfflineRewardQuery) ProtoMessage() {}

func (x *S2COfflineRewardQuery) ProtoReflect() protoreflect.Message {
	mi := &file_offline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2COfflineRewardQuery.ProtoReflect.Descriptor instead.
func (*S2COfflineRewardQuery) Descriptor() ([]byte, []int) {
	return file_offline_proto_rawDescGZIP(), []int{1}
}

func (x *S2COfflineRewardQuery) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2COfflineRewardQuery) GetOfflineSeconds() int64 {
	if x != nil {
		return x.OfflineSeconds
	}
	return 0
}

func (x *S2COfflineRewardQuery) GetRewards() []*common.RewardItem {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *S2COfflineRewardQuery) GetHangMultiplier() int32 {
	if x != nil {
		return x.HangMultiplier
	}
	return 0
}

// 一键领取离线收益
type C2SOfflineRewardClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTs      int64                  `protobuf:"varint,1,opt,name=client_ts,json=clientTs,proto3" json:"client_ts,omitempty"` // 客户端时间戳，仅作参考，服务端以自身时间结算
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SOfflineRewardClaim) Reset() {
	*x = C2SOfflineRewardClaim{}
	mi := &file_offline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SOfflineRewardClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SOfflineRewardClaim) ProtoMessage() {}

func (x *C2SOfflineRewardClaim) ProtoReflect() protoreflect.Message {
	mi := &file_offline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SOfflineRewardClaim.ProtoReflect.Descriptor instead.
func (*C2SOfflineRewardClaim) Descriptor() ([]byte, []int) {
	return file_offline_proto_rawDescGZIP(), []int{2}
}

func (x *C2SOfflineRewardClaim) GetClientTs() int64 {
	if x != nil {
		return x.ClientTs
	}
	return 0
}

type S2COfflineRewardClaim struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Result         *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Rewards        []*common.RewardItem   `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"`                                      // 实际到账
	SettledSeconds int64                  `protobuf:"varint,3,opt,name=settled_seconds,json=settledSeconds,proto3" json:"settled_seconds,omitempty"` // 本次覆盖的离线秒数
	NextSettleAt   int64                  `protobuf:"varint,4,opt,name=next_settle_at,json=nextSettleAt,proto3" json:"next_settle_at,omitempty"`     // 下次结算基准时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2COfflineRewardClaim) Reset() {
	*x = S2COfflineRewardClaim{}
	mi := &file_offline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2COfflineRewardClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2COfflineRewardClaim) ProtoMessage() {}

func (x *S2COfflineRewardClaim) ProtoReflect() protoreflect.Message {
	mi := &file_offline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2COfflineRewardClaim.ProtoReflect.Descriptor instead.
func (*S2COfflineRewardClaim) Descriptor() ([]byte, []int) {
	return file_offline_proto_rawDescGZIP(), []int{3}
}

func (x *S2COfflineRewardClaim) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2COfflineRewardClaim) GetRewards() []*common.RewardItem {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *S2COfflineRewardClaim) GetSettledSeconds() int64 {
	if x != nil {
		return x.SettledSeconds
	}
	return 0
}

func (x *S2COfflineRewardClaim) GetNextSettleAt() int64 {
	if x != nil {
		return x.NextSettleAt
	}
	return 0
}

// 在线挂机（限时/次数收益）查询与领取
type C2SHangRewardQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SHangRewardQuery) Reset() {
	*x = C2SHangRewardQuery{}
	mi := &file_offline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SHangRewardQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SHangRewardQuery) ProtoMessage() {}

func (x *C2SHangRewardQuery) ProtoReflect() protoreflect.Message {
	mi := &file_offline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SHangRewardQuery.ProtoReflect.Descriptor instead.
func (*C2SHangRewardQuery) Descriptor() ([]byte, []int) {
	return file_offline_proto_rawDescGZIP(), []int{4}
}

type S2CHangRewardQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Rewards       []*common.RewardItem   `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"`                                   // 当前可领取的在线挂机收益
	RemainSeconds int64                  `protobuf:"varint,3,opt,name=remain_seconds,json=remainSeconds,proto3" json:"remain_seconds,omitempty"` // 距离下次收益倒计时
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CHangRewardQuery) Reset() {
	*x = S2CHangRewardQuery{}
	mi := &file_offline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CHangRewardQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CHangRewardQuery) ProtoMessage() {}

func (x *S2CHangRewardQuery) ProtoReflect() protoreflect.Message {
	mi := &file_offline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CHangRewardQuery.ProtoReflect.Descriptor instead.
func (*S2CHangRewardQuery) Descriptor() ([]byte, []int) {
	return file_offline_proto_rawDescGZIP(), []int{5}
}

func (x *S2CHangRewardQuery) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CHangRewardQuery) GetRewards() []*common.RewardItem {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *S2CHangRewardQuery) GetRemainSeconds() int64 {
	if x != nil {
		return x.RemainSeconds
	}
	return 0
}

type C2SHangRewardClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SHangRewardClaim) Reset() {
	*x = C2SHangRewardClaim{}
	mi := &file_offline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SHangRewardClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SHangRewardClaim) ProtoMessage() {}

func (x *C2SHangRewardClaim) ProtoReflect() protoreflect.Message {
	mi := &file_offline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SHangRewardClaim.ProtoReflect.Descriptor instead.
func (*C2SHangRewardClaim) Descriptor() ([]byte, []int) {
	return file_offline_proto_rawDescGZIP(), []int{6}
}

type S2CHangRewardClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *common.Result         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Rewards       []*common.RewardItem   `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CHangRewardClaim) Reset() {
	*x = S2CHangRewardClaim{}
	mi := &file_offline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CHangRewardClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CHangRewardClaim) ProtoMessage() {}

func (x *S2CHangRewardClaim) ProtoReflect() protoreflect.Message {
	mi := &file_offline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CHangRewardClaim.ProtoReflect.Descriptor instead.
func (*S2CHangRewardClaim) Descriptor() ([]byte, []int) {
	return file_offline_proto_rawDescGZIP(), []int{7}
}

func (x *S2CHangRewardClaim) GetResult() *common.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CHangRewardClaim) GetRewards() []*common.RewardItem {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_offline_proto protoreflect.FileDescriptor

const file_offline_proto_rawDesc = "" +
	"\n" +
	"\roffline.proto\x12\x10chenxiao.offline\x1a\fcommon.proto\"\x17\n" +
	"\x15C2SOfflineRewardQuery\"\xd1\x01\n" +
	"\x15S2COfflineRewardQuery\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x12'\n" +
	"\x0foffline_seconds\x18\x02 \x01(\x03R\x0eofflineSeconds\x125\n" +
	"\arewards\x18\x03 \x03(\v2\x1b.chenxiao.common.RewardItemR\arewards\x12'\n" +
	"\x0fhang_multiplier\x18\x04 \x01(\x05R\x0ehangMultiplier\"4\n" +
	"\x15C2SOfflineRewardClaim\x12\x1b\n" +
	"\tclient_ts\x18\x01 \x01(\x03R\bclientTs\"\xce\x01\n" +
	"\x15S2COfflineRewardClaim\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x125\n" +
	"\arewards\x18\x02 \x03(\v2\x1b.chenxiao.common.RewardItemR\arewards\x12'\n" +
	"\x0fsettled_seconds\x18\x03 \x01(\x03R\x0esettledSeconds\x12$\n" +
	"\x0enext_settle_at\x18\x04 \x01(\x03R\fnextSettleAt\"\x14\n" +
	"\x12C2SHangRewardQuery\"\xa3\x01\n" +
	"\x12S2CHangRewardQuery\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x125\n" +
	"\arewards\x18\x02 \x03(\v2\x1b.chenxiao.common.RewardItemR\arewards\x12%\n" +
	"\x0eremain_seconds\x18\x03 \x01(\x03R\rremainSeconds\"\x14\n" +
	"\x12C2SHangRewardClaim\"|\n" +
	"\x12S2CHangRewardClaim\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.chenxiao.common.ResultR\x06result\x125\n" +
	"\arewards\x18\x02 \x03(\v2\x1b.chenxiao.common.RewardItemR\arewardsB Z\x1echenxiao/proto/offline;offlineb\x06proto3"

var (
	file_offline_proto_rawDescOnce sync.Once
	file_offline_proto_rawDescData []byte
)

func file_offline_proto_rawDescGZIP() []byte {
	file_offline_proto_rawDescOnce.Do(func() {
		file_offline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_offline_proto_rawDesc), len(file_offline_proto_rawDesc)))
	})
	return file_offline_proto_rawDescData
}

var file_offline_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_offline_proto_goTypes = []any{
	(*C2SOfflineRewardQuery)(nil), // 0: chenxiao.offline.C2SOfflineRewardQuery
	(*S2COfflineRewardQuery)(nil), // 1: chenxiao.offline.S2COfflineRewardQuery
	(*C2SOfflineRewardClaim)(nil), // 2: chenxiao.offline.C2SOfflineRewardClaim
	(*S2COfflineRewardClaim)(nil), // 3: chenxiao.offline.S2COfflineRewardClaim
	(*C2SHangRewardQuery)(nil),    // 4: chenxiao.offline.C2SHangRewardQuery
	(*S2CHangRewardQuery)(nil),    // 5: chenxiao.offline.S2CHangRewardQuery
	(*C2SHangRewardClaim)(nil),    // 6: chenxiao.offline.C2SHangRewardClaim
	(*S2CHangRewardClaim)(nil),    // 7: chenxiao.offline.S2CHangRewardClaim
	(*common.Result)(nil),         // 8: chenxiao.common.Result
	(*common.RewardItem)(nil),     // 9: chenxiao.common.RewardItem
}
var file_offline_proto_depIdxs = []int32{
	8, // 0: chenxiao.offline.S2COfflineRewardQuery.result:type_name -> chenxiao.common.Result
	9, // 1: chenxiao.offline.S2COfflineRewardQuery.rewards:type_name -> chenxiao.common.RewardItem
	8, // 2: chenxiao.offline.S2COfflineRewardClaim.result:type_name -> chenxiao.common.Result
	9, // 3: chenxiao.offline.S2COfflineRewardClaim.rewards:type_name -> chenxiao.common.RewardItem
	8, // 4: chenxiao.offline.S2CHangRewardQuery.result:type_name -> chenxiao.common.Result
	9, // 5: chenxiao.offline.S2CHangRewardQuery.rewards:type_name -> chenxiao.common.RewardItem
	8, // 6: chenxiao.offline.S2CHangRewardClaim.result:type_name -> chenxiao.common.Result
	9, // 7: chenxiao.offline.S2CHangRewardClaim.rewards:type_name -> chenxiao.common.RewardItem
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_offline_proto_init() }
func file_offline_proto_init() {
	if File_offline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_offline_proto_rawDesc), len(file_offline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_offline_proto_goTypes,
		DependencyIndexes: file_offline_proto_depIdxs,
		MessageInfos:      file_offline_proto_msgTypes,
	}.Build()
	File_offline_proto = out.File
	file_offline_proto_goTypes = nil
	file_offline_proto_depIdxs = nil
}
